Squid Web Cache: squid/src/cache_cf.cc File Reference
cache_cf.cc File Reference
#include "squid.h"
#include "acl/Acl.h"
#include "acl/AclDenyInfoList.h"
#include "acl/AclSizeLimit.h"
#include "acl/Address.h"
#include "acl/Gadgets.h"
#include "acl/MethodData.h"
#include "acl/Node.h"
#include "acl/Tree.h"
#include "anyp/PortCfg.h"
#include "anyp/UriScheme.h"
#include "auth/Config.h"
#include "auth/Scheme.h"
#include "AuthReg.h"
#include "base/CharacterSet.h"
#include "base/PackableStream.h"
#include "base/RunnersRegistry.h"
#include "cache_cf.h"
#include "CachePeer.h"
#include "CachePeers.h"
#include "compat/netdb.h"
#include "compat/socket.h"
#include "ConfigOption.h"
#include "ConfigParser.h"
#include "CpuAffinityMap.h"
#include "debug/Messages.h"
#include "DiskIO/DiskIOModule.h"
#include "eui/Config.h"
#include "ExternalACL.h"
#include "format/Format.h"
#include "fqdncache.h"
#include "ftp/Elements.h"
#include "globals.h"
#include "HeaderMangling.h"
#include "HttpUpgradeProtocolAccess.h"
#include "icmp/IcmpConfig.h"
#include "ip/Intercept.h"
#include "ip/NfMarkConfig.h"
#include "ip/QosConfig.h"
#include "ip/tools.h"
#include "ipc/Kids.h"
#include "log/Config.h"
#include "log/CustomLog.h"
#include "MemBuf.h"
#include "MessageDelayPools.h"
#include "mgr/ActionPasswordList.h"
#include "mgr/Registration.h"
#include "neighbors.h"
#include "NeighborTypeDomainList.h"
#include "Parsing.h"
#include "pconn.h"
#include "PeerDigest.h"
#include "PeerPoolMgr.h"
#include "redirect.h"
#include "RefreshPattern.h"
#include "rfc1738.h"
#include "sbuf/List.h"
#include "sbuf/Stream.h"
#include "SquidConfig.h"
#include "SquidString.h"
#include "ssl/ProxyCerts.h"
#include "Store.h"
#include "store/Disks.h"
#include "tools.h"
#include "util.h"
#include "wordlist.h"
#include "wccp2.h"
#include "adaptation/Config.h"
#include "adaptation/icap/Config.h"
#include "adaptation/ecap/Config.h"
#include "ssl/Config.h"
#include "ssl/support.h"
#include "snmp.h"
#include <algorithm>
#include <chrono>
#include <limits>
#include <list>
#include "ssl/gadgets.h"
#include "DelayConfig.h"
#include "DelayPools.h"
#include "ClientDelayConfig.h"
#include "cf_parser.cci"
#include "AccessLogEntry.h"
Classes
class sslBumpCfgRr
Macros
#define free_http_header_access free_HeaderManglers
#define free_http_header_replace free_HeaderManglers
#define parse_PortCfg(l) parsePortCfg((l), token)
#define free_PortCfg(h) *(h)=NULL
#define free_delay_pool_class(X)
#define free_delay_pool_access(X)
#define free_delay_pool_rates(X)
#define dump_delay_pool_class(X, Y, Z)
#define dump_delay_pool_access(X, Y, Z)
#define dump_delay_pool_rates(X, Y, Z)
#define free_client_delay_pool_access(X)
#define free_client_delay_pool_rates(X)
#define dump_client_delay_pool_access(X, Y, Z)
#define dump_client_delay_pool_rates(X, Y, Z)
#define free_onoff free_int
#define free_tristate free_int
#define free_pipelinePrefetch free_int
#define dump_pipelinePrefetch dump_int
#define dump_eol dump_string
#define free_eol free_string
#define dump_TokenOrQuotedString dump_string
#define free_TokenOrQuotedString free_string
#define free_b_size_t free_size_t
#define free_b_ssize_t free_ssize_t
#define free_kb_size_t free_size_t
#define free_mb_size_t free_size_t
#define free_gb_size_t free_size_t
#define free_kb_int64_t free_b_int64_t
#define free_wordlist wordlistDestroy
#define free_uri_whitespace free_int
Functions
static void parse_adaptation_service_set_type ()
static void parse_adaptation_service_chain_type ()
static void parse_adaptation_access_type ()
static void parse_icap_service_type (Adaptation::Icap::Config *)
static void dump_icap_service_type (StoreEntry *, const char *, const Adaptation::Icap::Config &)
static void free_icap_service_type (Adaptation::Icap::Config *)
static void parse_icap_class_type ()
static void parse_icap_access_type ()
static void parse_icap_service_failure_limit (Adaptation::Icap::Config *)
static void dump_icap_service_failure_limit (StoreEntry *, const char *, const Adaptation::Icap::Config &)
static void free_icap_service_failure_limit (Adaptation::Icap::Config *)
static void parse_ecap_service_type (Adaptation::Ecap::Config *)
static void dump_ecap_service_type (StoreEntry *, const char *, const Adaptation::Ecap::Config &)
static void free_ecap_service_type (Adaptation::Ecap::Config *)
static peer_t parseNeighborType (const char *s)
static void parse_cache_log_message (DebugMessages **messages)
static void dump_cache_log_message (StoreEntry *entry, const char *name, const DebugMessages *messages)
static void free_cache_log_message (DebugMessages **messages)
static void parse_access_log (CustomLog **customlog_definitions)
static int check_null_access_log (CustomLog *customlog_definitions)
static void dump_access_log (StoreEntry *entry, const char *name, CustomLog *definitions)
static void free_access_log (CustomLog **definitions)
static void configDoConfigure (void)
static void parse_refreshpattern (RefreshPattern **)
static void parse_u_short (unsigned short *var)
static void parse_string (char **)
static void default_all (void)
static void defaults_if_none (void)
static void defaults_postscriptum (void)
static int parse_line (char *)
static void parse_obsolete (const char *)
static void parseBytesLine (size_t *bptr, const char *units)
static void parseBytesLineSigned (ssize_t *bptr, const char *units)
static size_t parseBytesUnits (const char *unit)
static void free_all (void)
void requirePathnameExists (const char *name, const char *path)
static void free_HeaderManglers (HeaderManglers **pm)
static void dump_http_header_access (StoreEntry *entry, const char *name, const HeaderManglers *manglers)
static void parse_http_header_access (HeaderManglers **manglers)
static void dump_http_header_replace (StoreEntry *entry, const char *name, const HeaderManglers *manglers)
static void parse_http_header_replace (HeaderManglers **manglers)
static void dump_HeaderWithAclList (StoreEntry *entry, const char *name, HeaderWithAclList *headers)
static void parse_HeaderWithAclList (HeaderWithAclList **header)
static void free_HeaderWithAclList (HeaderWithAclList **header)
static void parse_note (Notes *)
static void dump_note (StoreEntry *, const char *, Notes &)
static void free_note (Notes *)
static void parse_denyinfo (AclDenyInfoList **var)
static void dump_denyinfo (StoreEntry *entry, const char *name, AclDenyInfoList *var)
static void free_denyinfo (AclDenyInfoList **var)
static void parse_IpAddress_list (Ip::Address_list **)
static void dump_IpAddress_list (StoreEntry *, const char *, const Ip::Address_list *)
static void free_IpAddress_list (Ip::Address_list **)
static void parsePortCfg (AnyP::PortCfgPointer *, const char *protocol)
static void dump_PortCfg (StoreEntry *, const char *, const AnyP::PortCfgPointer &)
static void parse_sslproxy_cert_sign (sslproxy_cert_sign **cert_sign)
static void dump_sslproxy_cert_sign (StoreEntry *entry, const char *name, sslproxy_cert_sign *cert_sign)
static void free_sslproxy_cert_sign (sslproxy_cert_sign **cert_sign)
static void parse_sslproxy_cert_adapt (sslproxy_cert_adapt **cert_adapt)
static void dump_sslproxy_cert_adapt (StoreEntry *entry, const char *name, sslproxy_cert_adapt *cert_adapt)
static void free_sslproxy_cert_adapt (sslproxy_cert_adapt **cert_adapt)
static void parse_sslproxy_ssl_bump (acl_access **ssl_bump)
static void dump_sslproxy_ssl_bump (StoreEntry *entry, const char *name, acl_access *ssl_bump)
static void free_sslproxy_ssl_bump (acl_access **ssl_bump)
static void parse_ftp_epsv (acl_access **ftp_epsv)
static void dump_ftp_epsv (StoreEntry *entry, const char *name, acl_access *ftp_epsv)
static void free_ftp_epsv (acl_access **ftp_epsv)
static void parse_b_size_t (size_t *var)
static void parse_b_int64_t (int64_t *var)
static void parse_CpuAffinityMap (CpuAffinityMap **const cpuAffinityMap)
static void dump_CpuAffinityMap (StoreEntry *const entry, const char *const name, const CpuAffinityMap *const cpuAffinityMap)
static void free_CpuAffinityMap (CpuAffinityMap **const cpuAffinityMap)
static void parse_UrlHelperTimeout (SquidConfig::UrlHelperTimeout *)
static void dump_UrlHelperTimeout (StoreEntry *, const char *, SquidConfig::UrlHelperTimeout &)
static void free_UrlHelperTimeout (SquidConfig::UrlHelperTimeout *)
static int parseOneConfigFile (const char *file_name, unsigned int depth)
static void parse_configuration_includes_quoted_values (bool *recognizeQuotedValues)
static void dump_configuration_includes_quoted_values (StoreEntry *const entry, const char *const name, bool recognizeQuotedValues)
static void free_configuration_includes_quoted_values (bool *recognizeQuotedValues)
static void parse_on_unsupported_protocol (acl_access **access)
static void dump_on_unsupported_protocol (StoreEntry *entry, const char *name, acl_access *access)
static void free_on_unsupported_protocol (acl_access **access)
static void ParseAclWithAction (acl_access **access, const Acl::Answer &action, const char *desc, Acl::Node *acl=nullptr)
static void parse_http_upgrade_request_protocols (HttpUpgradeProtocolAccess **protoGuards)
static void dump_http_upgrade_request_protocols (StoreEntry *entry, const char *name, HttpUpgradeProtocolAccess *protoGuards)
static void free_http_upgrade_request_protocols (HttpUpgradeProtocolAccess **protoGuards)
void self_destruct (void)
static void SetConfigFilename (char const *file_name, bool is_pipe)
static bool IsSpace (const char ch)
static const char * skip_ws (const char *s)
static int parseManyConfigFiles (char *files, int depth)
static void ReplaceSubstr (char *&str, int &len, unsigned substrIdx, unsigned substrLen, const char *newSubstr)
static void SubstituteMacro (char *&line, int &len, const char *macroName, const char *substStr)
static void ProcessMacros (char *&line, int &len)
static void trim_trailing_ws (char *str)
static const char * FindStatement (const char *line, const char *statement)
static bool StrToInt (const char *str, long &number)
static bool EvalBoolExpr (const char *expr)
template<typename T >
static bool SawDirective (const T &raw)
whether we have seen (and, hence, configured) the given directive
template<typename T >
static void ParseDirective (T &raw, ConfigParser &parser)
template<typename T >
static void DumpDirective (const T &raw, StoreEntry *entry, const char *name)
template<typename T >
static void FreeDirective (T &raw)
frees any resources associated with the given raw SquidConfig data member
template<class MinimalUnit >
static const char * TimeUnitToString ()
template<class MinimalUnit >
static bool parseTimeUnit (const char *unitName, std::chrono::nanoseconds &ns)
static std::chrono::nanoseconds ToNanoSeconds (const double value, const std::chrono::nanoseconds &unit)
template<class TimeUnit >
static TimeUnit FromNanoseconds (const std::chrono::nanoseconds &ns, const double parsedValue)
template<class TimeUnit >
static TimeUnit parseTimeLine ()
static void parseBytesLine64 (int64_t *bptr, const char *units)
void parseBytesOptionValue (size_t *bptr, const char *units, char const *value)
Parse bytes number from a string.
static void parse_SBufList (SBufList *list)
static void dump_SBufList (StoreEntry *entry, const SBufList &words)
static void dump_SBufList (StoreEntry *entry, const char *name, SBufList &list)
static void free_SBufList (SBufList *list)
static void dump_acl (StoreEntry *entry, const char *directiveName, Acl::NamedAcls *config)
static void parse_acl (Acl::NamedAcls **config)
static void free_acl (Acl::NamedAcls **config)
void dump_acl_list (StoreEntry *entry, ACLList *head)
void dump_acl_access (StoreEntry *entry, const char *name, acl_access *head)
static void parse_acl_access (acl_access **head)
static void free_acl_access (acl_access **head)
static void dump_address (StoreEntry *entry, const char *name, Ip::Address &addr)
static void parse_address (Ip::Address *addr)
static void free_address (Ip::Address *addr)
static void dump_acl_address (StoreEntry *entry, const char *name, Acl::Address *head)
static void parse_acl_address (Acl::Address **head)
static void free_acl_address (Acl::Address **head)
static void dump_acl_tos (StoreEntry *entry, const char *name, acl_tos *head)
static void parse_acl_tos (acl_tos **head)
static void free_acl_tos (acl_tos **head)
static void dump_acl_b_size_t (StoreEntry *entry, const char *name, AclSizeLimit *head)
static void parse_acl_b_size_t (AclSizeLimit **head)
static void free_acl_b_size_t (AclSizeLimit **head)
static void free_delay_pool_count (DelayConfig *cfg)
static void dump_delay_pool_count (StoreEntry *entry, const char *name, DelayConfig &cfg)
static void parse_delay_pool_count (DelayConfig *cfg)
static void parse_delay_pool_class (DelayConfig *cfg)
static void parse_delay_pool_rates (DelayConfig *cfg)
static void parse_delay_pool_access (DelayConfig *cfg)
static void free_client_delay_pool_count (ClientDelayConfig *cfg)
static void dump_client_delay_pool_count (StoreEntry *entry, const char *name, ClientDelayConfig &cfg)
static void parse_client_delay_pool_count (ClientDelayConfig *cfg)
static void parse_client_delay_pool_rates (ClientDelayConfig *cfg)
static void parse_client_delay_pool_access (ClientDelayConfig *cfg)
static void dump_cachedir (StoreEntry *entry, const char *name, const Store::DiskConfig &swap)
static int check_null_string (char *s)
static void parse_authparam (Auth::ConfigVector *config)
static void free_authparam (Auth::ConfigVector *cfg)
static void dump_authparam (StoreEntry *entry, const char *name, Auth::ConfigVector cfg)
static void parse_AuthSchemes (acl_access **authSchemes)
static void free_AuthSchemes (acl_access **authSchemes)
static void dump_AuthSchemes (StoreEntry *entry, const char *name, acl_access *authSchemes)
static void parse_cachedir (Store::DiskConfig *swap)
static const char * peer_type_str (const peer_t type)
static void dump_peer (StoreEntry *entry, const char *name, const CachePeers *peers)
static bool isUnsignedNumeric (const char *str, size_t len)
static unsigned short GetService (const char *proto)
unsigned short GetTcpService (void)
unsigned short GetUdpService (void)
static void parse_peer (CachePeers **peers)
static void free_peer (CachePeers **const peers)
static void dump_cachemgrpasswd (StoreEntry *entry, const char *name, Mgr::ActionPasswordList *list)
static void parse_cachemgrpasswd (Mgr::ActionPasswordList **head)
static void free_cachemgrpasswd (Mgr::ActionPasswordList **head)
static void parse_peer_access (void)
static void parse_hostdomaintype (void)
static void dump_int (StoreEntry *entry, const char *name, int var)
void parse_int (int *var)
static void free_int (int *var)
static void dump_int64_t (StoreEntry *entry, const char *name, int64_t var)
static void parse_int64_t (int64_t *var)
static void free_int64_t (int64_t *var)
static void dump_onoff (StoreEntry *entry, const char *name, int var)
void parse_onoff (int *var)
static void dump_tristate (StoreEntry *entry, const char *name, int var)
static void parse_tristate (int *var)
static void parse_pipelinePrefetch (int *var)
static void dump_refreshpattern (StoreEntry *entry, const char *name, RefreshPattern *head)
static void free_refreshpattern (RefreshPattern **head)
static void dump_string (StoreEntry *entry, const char *name, char *var)
static void free_string (char **var)
void parse_eol (char *volatile *var)
static void parse_TokenOrQuotedString (char **var)
static void dump_time_t (StoreEntry *entry, const char *name, time_t var)
void parse_time_t (time_t *var)
static void free_time_t (time_t *var)
static void dump_time_msec (StoreEntry *entry, const char *name, time_msec_t var)
static void parse_time_msec (time_msec_t *var)
static void free_time_msec (time_msec_t *var)
static void dump_time_nanoseconds (StoreEntry *entry, const char *name, const std::chrono::nanoseconds &var)
static void parse_time_nanoseconds (std::chrono::nanoseconds *var)
static void free_time_nanoseconds (std::chrono::nanoseconds *var)
static void dump_b_size_t (StoreEntry *entry, const char *name, size_t var)
static void dump_b_ssize_t (StoreEntry *entry, const char *name, ssize_t var)
static void dump_b_int64_t (StoreEntry *entry, const char *name, int64_t var)
static void dump_kb_int64_t (StoreEntry *entry, const char *name, int64_t var)
static void parse_b_ssize_t (ssize_t *var)
static void parse_kb_int64_t (int64_t *var)
static void free_size_t (size_t *var)
static void free_ssize_t (ssize_t *var)
static void free_b_int64_t (int64_t *var)
static void dump_u_short (StoreEntry *entry, const char *name, unsigned short var)
static void free_u_short (unsigned short *u)
static void dump_wordlist (StoreEntry *entry, const char *name, wordlist *list)
void parse_wordlist (wordlist **list)
static int check_null_acl_access (acl_access *a)
static void parse_uri_whitespace (int *var)
static void dump_uri_whitespace (StoreEntry *entry, const char *name, int var)
static void free_removalpolicy (RemovalPolicySettings **settings)
static void parse_removalpolicy (RemovalPolicySettings **settings)
static void dump_removalpolicy (StoreEntry *entry, const char *name, RemovalPolicySettings *settings)
void free_YesNoNone (YesNoNone *)
static void parse_YesNoNone (YesNoNone *option)
static void dump_YesNoNone (StoreEntry *entry, const char *name, YesNoNone &option)
static void free_memcachemode (SquidConfig *)
static void parse_memcachemode (SquidConfig *)
static void dump_memcachemode (StoreEntry *entry, const char *name, SquidConfig &)
static void parsePortSpecification (const AnyP::PortCfgPointer &s, char *token)
static AnyP::ProtocolVersion parsePortProtocol (const SBuf &value)
static void parse_port_option (AnyP::PortCfgPointer &s, char *token)
void add_http_port (char *portspec)
static void dump_generic_port (StoreEntry *e, const char *n, const AnyP::PortCfgPointer &s)
void configFreeMemory (void)
DefineRunnerRegistrator (sslBumpCfgRr)
static DebugMessageId ParseDebugMessageId (const char *value, const char eov)
static std::chrono::seconds ParseUrlRewriteTimeout ()
Variables
static const char *const T_NANOSECOND_STR = "nanosecond"
static const char *const T_MICROSECOND_STR = "microsecond"
static const char *const T_MILLISECOND_STR = "millisecond"
static const char *const T_SECOND_STR = "second"
static const char *const T_MINUTE_STR = "minute"
static const char *const T_HOUR_STR = "hour"
static const char *const T_DAY_STR = "day"
static const char *const T_WEEK_STR = "week"
static const char *const T_FORTNIGHT_STR = "fortnight"
static const char *const T_MONTH_STR = "month"
static const char *const T_YEAR_STR = "year"
static const char *const T_DECADE_STR = "decade"
static const char *const B_BYTES_STR = "bytes"
static const char *const B_KBYTES_STR = "KB"
static const char *const B_MBYTES_STR = "MB"
static const char *const B_GBYTES_STR = "GB"
static const double HoursPerYear = 24*365.2522
static OBJH dump_config
static ConfigParser LegacyParser = ConfigParser()
const char * cfg_directive = nullptr
During parsing, the name of the current squid.conf directive being parsed.
const char * cfg_filename = nullptr
int config_lineno = 0
char config_input_line [BUFSIZ] = {}
static bool FtpEspvDeprecated = false
Macro Definition Documentation
dump_client_delay_pool_access
#define dump_client_delay_pool_access (X, Y, Z)
Definition at line 1794 of file cache_cf.cc.
dump_client_delay_pool_rates
#define dump_client_delay_pool_rates (X, Y, Z)
Definition at line 1795 of file cache_cf.cc.
dump_delay_pool_access
#define dump_delay_pool_access (X, Y, Z)
Definition at line 1745 of file cache_cf.cc.
dump_delay_pool_class
#define dump_delay_pool_class (X, Y, Z)
Definition at line 1744 of file cache_cf.cc.
dump_delay_pool_rates
#define dump_delay_pool_rates (X, Y, Z)
Definition at line 1746 of file cache_cf.cc.
dump_eol
#define dump_eol dump_string
Definition at line 2912 of file cache_cf.cc.
dump_pipelinePrefetch
#define dump_pipelinePrefetch dump_int
Definition at line 2662 of file cache_cf.cc.
dump_TokenOrQuotedString
#define dump_TokenOrQuotedString dump_string
Definition at line 2929 of file cache_cf.cc.
free_b_size_t
#define free_b_size_t free_size_t
Definition at line 3062 of file cache_cf.cc.
free_b_ssize_t
#define free_b_ssize_t free_ssize_t
Definition at line 3063 of file cache_cf.cc.
free_client_delay_pool_access
#define free_client_delay_pool_access (X)
Definition at line 1792 of file cache_cf.cc.
free_client_delay_pool_rates
#define free_client_delay_pool_rates (X)
Definition at line 1793 of file cache_cf.cc.
free_delay_pool_access
#define free_delay_pool_access (X)
Definition at line 1742 of file cache_cf.cc.
free_delay_pool_class
#define free_delay_pool_class (X)
Definition at line 1741 of file cache_cf.cc.
free_delay_pool_rates
#define free_delay_pool_rates (X)
Definition at line 1743 of file cache_cf.cc.
free_eol
#define free_eol free_string
Definition at line 2913 of file cache_cf.cc.
free_gb_size_t
#define free_gb_size_t free_size_t
Definition at line 3066 of file cache_cf.cc.
free_http_header_access
#define free_http_header_access free_HeaderManglers
Definition at line 192 of file cache_cf.cc.
free_http_header_replace
#define free_http_header_replace free_HeaderManglers
Definition at line 195 of file cache_cf.cc.
free_kb_int64_t
#define free_kb_int64_t free_b_int64_t
Definition at line 3067 of file cache_cf.cc.
free_kb_size_t
#define free_kb_size_t free_size_t
Definition at line 3064 of file cache_cf.cc.
free_mb_size_t
#define free_mb_size_t free_size_t
Definition at line 3065 of file cache_cf.cc.
free_onoff
#define free_onoff free_int
Definition at line 2592 of file cache_cf.cc.
free_pipelinePrefetch
#define free_pipelinePrefetch free_int
Definition at line 2661 of file cache_cf.cc.
free_PortCfg
#define free_PortCfg (h) *(h)=NULL
Definition at line 219 of file cache_cf.cc.
free_TokenOrQuotedString
#define free_TokenOrQuotedString free_string
Definition at line 2930 of file cache_cf.cc.
free_tristate
#define free_tristate free_int
Definition at line 2636 of file cache_cf.cc.
free_uri_whitespace
#define free_uri_whitespace free_int
Definition at line 3137 of file cache_cf.cc.
free_wordlist
#define free_wordlist wordlistDestroy
Definition at line 3135 of file cache_cf.cc.
parse_PortCfg
#define parse_PortCfg (l) parsePortCfg((l), token)
Definition at line 217 of file cache_cf.cc.
Function Documentation
add_http_port()
void add_http_port (char * portspec)
Definition at line 3698 of file cache_cf.cc.
References assert, HttpPortList, parsePortProtocol(), and parsePortSpecification().
Referenced by mainHandleCommandLineOption().
check_null_access_log()
static int check_null_access_log (CustomLog * customlog_definitions) static
Definition at line 4010 of file cache_cf.cc.
check_null_acl_access()
static int check_null_acl_access (acl_access * a) static
Definition at line 3130 of file cache_cf.cc.
check_null_string()
static int check_null_string (char * s) static
Definition at line 1903 of file cache_cf.cc.
configDoConfigure()
static void configDoConfigure (void) static
Definition at line 712 of file cache_cf.cc.
References SquidConfig::Accel, SquidConfig::accesslogs, Auth::SchemeConfig::active(), APP_FULLNAME, SquidConfig::appendDomain, SquidConfig::appendDomainLen, appname_string, SquidConfig2::clear(), SquidConfig::client_pconns, Config, Config2, SquidConfig::connect_retries, Security::PeerOptions::createClientContext(), CurrentCachePeers(), DBG_CRITICAL, DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, SquidConfig::defaultPeerContext, SquidConfig::directory, SquidConfig::effectiveGroup, SquidConfig2::effectiveGroupID, SquidConfig::effectiveUser, SquidConfig2::effectiveUserID, SquidConfig2::enable_purge, SquidConfig::errHtmlText, SquidConfig::errorDirectory, fatal(), fatalf(), Auth::SchemeConfig::Find(), RefreshPattern::flags, SquidConfig::foreignIntermediateCertsPath, getMyHostname(), SquidConfig::httpd_suppress_version_string, HttpPortList, SquidConfig::icaplogs, SquidConfig::icons, RefreshPattern::ignore_no_store, RefreshPattern::ignore_private, RefreshPattern::ignore_reload, wordlist::key, Ssl::loadSquidUntrusted(), log(), SquidConfig::Log, SquidConfig::max_filedescriptors, SquidConfig::maxObjectSize, SquidConfig::maxReplyHeaderSize, SquidConfig::maxRequestBufferSize, SquidConfig::maxRequestHeaderSize, memConfigure(), SquidConfig::mimeTablePathname, Helper::ChildConfig::n_max, RefreshPattern::next, null_string, SquidConfig::onoff, SquidConfig2::onoff, RefreshPattern::override_expire, RefreshPattern::override_lastmod, SquidConfig::pipeline_max_prefetch, SquidConfig::Program, Security::ProxyOutgoingConfig(), SquidConfig::redirect, SquidConfig::redirectChildren, SquidConfig::Refresh, RefreshPattern::reload_into_ims, requirePathnameExists(), Debug::rotateNumber, SquidConfig::rotateNumber, Auth::Config::schemeLists, self_destruct(), String::SizeMaxXXX(), SQUID_UDP_SO_SNDBUF, SquidConfig::ssl_client, SquidConfig::sslContext_, SquidConfig::Store, SquidConfig::store_id, storeConfigure(), SquidConfig::storeIdChildren, SquidConfig::surrogate_id, Auth::TheConfig, Log::TheConfig, ACLMethodData::ThePurgeCount, ThisCache, ThisCache2, SquidConfig::udpMaxHitObjsz, uniqueHostname(), SquidConfig::unlinkd, Ssl::useSquidUntrusted(), SquidConfig::via, visible_appname_string, wordlistDestroy(), and xstrdup.
Referenced by Configuration::Parse().
configFreeMemory()
void configFreeMemory (void)
Definition at line 3900 of file cache_cf.cc.
References Config, SquidConfig::defaultPeerContext, free_all(), Dns::ResolveClientAddressesAsap, SquidConfig::ssl_client, SquidConfig::sslContext_, and Ssl::unloadSquidUntrusted().
Referenced by Configuration::Parse().
default_all()
static void default_all (void) static
Referenced by Configuration::Parse().
defaults_if_none()
static void defaults_if_none (void) static
Referenced by Configuration::Parse().
defaults_postscriptum()
static void defaults_postscriptum (void) static
Referenced by Configuration::Parse().
DefineRunnerRegistrator()
DefineRunnerRegistrator (sslBumpCfgRr)
dump_access_log()
static void dump_access_log (StoreEntry * entry, const char * name, CustomLog * definitions) static
Definition at line 4016 of file cache_cf.cc.
References assert, dump_acl_list(), log(), CustomLog::next, and storeAppendPrintf().
dump_acl()
static void dump_acl (StoreEntry * entry, const char * directiveName, Acl::NamedAcls * config) static
Definition at line 1471 of file cache_cf.cc.
References Acl::DumpNamedAcls().
dump_acl_address()
static void dump_acl_address (StoreEntry * entry, const char * name, Acl::Address * head) static
Definition at line 1555 of file cache_cf.cc.
References dump_acl_list(), head, MAX_IPSTRLEN, squidaio_request_t::next, and storeAppendPrintf().
dump_acl_b_size_t()
static void dump_acl_b_size_t (StoreEntry * entry, const char * name, AclSizeLimit * head) static
Definition at line 1697 of file cache_cf.cc.
References acl_nfmark::aclList, B_BYTES_STR, dump_acl_list(), head, acl_nfmark::next, and storeAppendPrintf().
dump_acl_tos()
static void dump_acl_tos (StoreEntry * entry, const char * name, acl_tos * head) static
Definition at line 1593 of file cache_cf.cc.
References acl_tos::aclList, dump_acl_list(), head, acl_tos::next, storeAppendPrintf(), and acl_tos::tos.
dump_address()
static void dump_address (StoreEntry * entry, const char * name, Ip::Address & addr) static
Definition at line 1518 of file cache_cf.cc.
References MAX_IPSTRLEN, storeAppendPrintf(), and Ip::Address::toStr().
dump_authparam()
static void dump_authparam (StoreEntry * entry, const char * name, Auth::ConfigVector cfg) static
Definition at line 1962 of file cache_cf.cc.
dump_AuthSchemes()
static void dump_AuthSchemes (StoreEntry * entry, const char * name, acl_access * authSchemes) static
Definition at line 1990 of file cache_cf.cc.
References dump_SBufList(), Acl::Answer::kind, Auth::Config::schemeLists, and Auth::TheConfig.
dump_b_int64_t()
static void dump_b_int64_t (StoreEntry * entry, const char * name, int64_t var) static
Definition at line 3009 of file cache_cf.cc.
References B_BYTES_STR, PRId64, and storeAppendPrintf().
dump_b_size_t()
static void dump_b_size_t (StoreEntry * entry, const char * name, size_t var) static
Definition at line 2997 of file cache_cf.cc.
References B_BYTES_STR, and storeAppendPrintf().
dump_b_ssize_t()
static void dump_b_ssize_t (StoreEntry * entry, const char * name, ssize_t var) static
Definition at line 3003 of file cache_cf.cc.
References B_BYTES_STR, and storeAppendPrintf().
dump_cache_log_message()
static void dump_cache_log_message (StoreEntry * entry, const char * name, const DebugMessages * messages) static
Definition at line 4634 of file cache_cf.cc.
References StoreEntry::append(), SBufStream::buf(), and DebugMessages::messages.
dump_cachedir()
static void dump_cachedir (StoreEntry * entry, const char * name, const Store::DiskConfig & swap) static
Definition at line 1897 of file cache_cf.cc.
References Store::Disks::Dump().
dump_cachemgrpasswd()
static void dump_cachemgrpasswd (StoreEntry * entry, const char * name, Mgr::ActionPasswordList * list) static
Definition at line 2403 of file cache_cf.cc.
References Mgr::ActionPasswordList::actions, Packable::appendf(), Mgr::ActionPasswordList::next, Mgr::ActionPasswordList::passwd, SQUIDSBUFPH, SQUIDSBUFPRINT, and storeAppendPrintf().
dump_client_delay_pool_count()
static void dump_client_delay_pool_count (StoreEntry * entry, const char * name, ClientDelayConfig & cfg) static
Definition at line 1804 of file cache_cf.cc.
References ClientDelayConfig::dumpPoolCount().
dump_configuration_includes_quoted_values()
static void dump_configuration_includes_quoted_values (StoreEntry *const entry, const char *const name, bool recognizeQuotedValues) static
Definition at line 4843 of file cache_cf.cc.
References dump_onoff(), and ConfigParser::RecognizeQuotedValues.
dump_CpuAffinityMap()
static void dump_CpuAffinityMap (StoreEntry *const entry, const char *const name, const CpuAffinityMap *const cpuAffinityMap) static
Definition at line 4101 of file cache_cf.cc.
References CpuAffinityMap::cores(), CpuAffinityMap::processes(), size, and storeAppendPrintf().
dump_delay_pool_count()
static void dump_delay_pool_count (StoreEntry * entry, const char * name, DelayConfig & cfg) static
Definition at line 1755 of file cache_cf.cc.
References DelayConfig::dumpPoolCount().
dump_denyinfo()
static void dump_denyinfo (StoreEntry * entry, const char * name, AclDenyInfoList * var) static
Definition at line 2462 of file cache_cf.cc.
References AclDenyInfoList::acl_list, AclDenyInfoList::err_page_name, AclDenyInfoList::next, SQUIDSBUFPH, SQUIDSBUFPRINT, and storeAppendPrintf().
dump_ecap_service_type()
static void dump_ecap_service_type (StoreEntry * entry, const char * name, const Adaptation::Ecap::Config & cfg) static
Definition at line 4199 of file cache_cf.cc.
References Adaptation::Config::dumpService().
dump_ftp_epsv()
static void dump_ftp_epsv (StoreEntry * entry, const char * name, acl_access * ftp_epsv) static
Definition at line 4715 of file cache_cf.cc.
References Acl::AllowOrDeny(), and dump_SBufList().
dump_generic_port()
static void dump_generic_port (StoreEntry * e, const char * n, const AnyP::PortCfgPointer & s) static
Definition at line 3800 of file cache_cf.cc.
References DISABLE_PMTU_ALWAYS, DISABLE_PMTU_OFF, MAX_IPSTRLEN, AnyP::PROTO_HTTP, AnyP::ProtocolType_str, and storeAppendPrintf().
Referenced by dump_PortCfg().
dump_HeaderWithAclList()
static void dump_HeaderWithAclList (StoreEntry * entry, const char * name, HeaderWithAclList * headers) static
Definition at line 4486 of file cache_cf.cc.
References dump_acl_list(), and storeAppendPrintf().
dump_http_header_access()
static void dump_http_header_access (StoreEntry * entry, const char * name, const HeaderManglers * manglers) static
Definition at line 1830 of file cache_cf.cc.
References HeaderManglers::dumpAccess().
dump_http_header_replace()
static void dump_http_header_replace (StoreEntry * entry, const char * name, const HeaderManglers * manglers) static
Definition at line 1869 of file cache_cf.cc.
References HeaderManglers::dumpReplacement().
dump_http_upgrade_request_protocols()
static void dump_http_upgrade_request_protocols (StoreEntry * entry, const char * name, HttpUpgradeProtocolAccess * protoGuards) static
Definition at line 4913 of file cache_cf.cc.
References Acl::AllowOrDeny(), dump_SBufList(), HttpUpgradeProtocolAccess::forEach(), and Acl::Tree::treeDump().
dump_icap_service_failure_limit()
static void dump_icap_service_failure_limit (StoreEntry * entry, const char * name, const Adaptation::Icap::Config & cfg) static
Definition at line 4224 of file cache_cf.cc.
References Adaptation::Config::oldest_service_failure, Adaptation::Config::service_failure_limit, and storeAppendPrintf().
dump_icap_service_type()
static void dump_icap_service_type (StoreEntry * entry, const char * name, const Adaptation::Icap::Config & cfg) static
Definition at line 4161 of file cache_cf.cc.
References Adaptation::Config::dumpService().
dump_int()
static void dump_int (StoreEntry * entry, const char * name, int var) static
Definition at line 2522 of file cache_cf.cc.
References storeAppendPrintf().
dump_int64_t()
static void dump_int64_t (StoreEntry * entry, const char * name, int64_t var) static
Definition at line 2542 of file cache_cf.cc.
References PRId64, and storeAppendPrintf().
dump_IpAddress_list()
static void dump_IpAddress_list (StoreEntry * e, const char * n, const Ip::Address_list * s) static
Definition at line 3342 of file cache_cf.cc.
References MAX_IPSTRLEN, Ip::Address_list::next, Ip::Address_list::s, storeAppendPrintf(), and Ip::Address::toStr().
dump_kb_int64_t()
static void dump_kb_int64_t (StoreEntry * entry, const char * name, int64_t var) static
Definition at line 3015 of file cache_cf.cc.
References B_KBYTES_STR, PRId64, and storeAppendPrintf().
dump_memcachemode()
static void dump_memcachemode (StoreEntry * entry, const char * name, SquidConfig &) static
Definition at line 3277 of file cache_cf.cc.
References Config, SquidConfig::memory_cache_disk, SquidConfig::memory_cache_first, SquidConfig::onoff, and storeAppendPrintf().
dump_note()
static void dump_note (StoreEntry * entry, const char * name, Notes & notes) static
Definition at line 4557 of file cache_cf.cc.
References Notes::printAsNoteDirectives().
dump_on_unsupported_protocol()
static void dump_on_unsupported_protocol (StoreEntry * entry, const char * name, acl_access * access) static
Definition at line 4881 of file cache_cf.cc.
References dump_SBufList(), Acl::Answer::kind, and Acl::Tree::treeDump().
dump_onoff()
static void dump_onoff (StoreEntry * entry, const char * name, int var) static
Definition at line 2562 of file cache_cf.cc.
References storeAppendPrintf().
Referenced by dump_configuration_includes_quoted_values(), and dump_YesNoNone().
dump_peer()
static void dump_peer (StoreEntry * entry, const char * name, const CachePeers * peers) static
Definition at line 2056 of file cache_cf.cc.
References NeighborTypeDomainList::domain, dump_acl_access(), dump_peer_options(), LOCAL_ARRAY, neighborTypeStr(), NeighborTypeDomainList::next, peer_type_str(), storeAppendPrintf(), and NeighborTypeDomainList::type.
dump_PortCfg()
static void dump_PortCfg (StoreEntry * e, const char * n, const AnyP::PortCfgPointer & s) static
Definition at line 3891 of file cache_cf.cc.
References dump_generic_port(), and storeAppendPrintf().
dump_refreshpattern()
static void dump_refreshpattern (StoreEntry * entry, const char * name, RefreshPattern * head) static
Definition at line 2665 of file cache_cf.cc.
References head, squidaio_request_t::next, and storeAppendPrintf().
dump_removalpolicy()
static void dump_removalpolicy (StoreEntry * entry, const char * name, RemovalPolicySettings * settings) static
Definition at line 3212 of file cache_cf.cc.
References RemovalPolicySettings::args, wordlist::key, wordlist::next, storeAppendPrintf(), and RemovalPolicySettings::type.
dump_SBufList() [1/2]
static void dump_SBufList (StoreEntry * entry, const char * name, SBufList & list) static
Definition at line 1454 of file cache_cf.cc.
References StoreEntry::append(), and dump_SBufList().
dump_SBufList() [2/2]
static void dump_SBufList (StoreEntry * entry, const SBufList & words) static
Definition at line 1443 of file cache_cf.cc.
References StoreEntry::append().
Referenced by dump_acl_access(), dump_acl_list(), dump_AuthSchemes(), dump_ftp_epsv(), dump_http_upgrade_request_protocols(), dump_on_unsupported_protocol(), dump_SBufList(), and dump_sslproxy_ssl_bump().
dump_sslproxy_cert_adapt()
static void dump_sslproxy_cert_adapt (StoreEntry * entry, const char * name, sslproxy_cert_adapt * cert_adapt) static
Definition at line 4294 of file cache_cf.cc.
References dump_acl_list(), sslproxy_cert_adapt::next, Ssl::sslCertAdaptAlgoritm(), and storeAppendPrintf().
dump_sslproxy_cert_sign()
static void dump_sslproxy_cert_sign (StoreEntry * entry, const char * name, sslproxy_cert_sign * cert_sign) static
Definition at line 4340 of file cache_cf.cc.
References Ssl::certSignAlgorithm(), dump_acl_list(), sslproxy_cert_sign::next, and storeAppendPrintf().
dump_sslproxy_ssl_bump()
static void dump_sslproxy_ssl_bump (StoreEntry * entry, const char * name, acl_access * ssl_bump) static
Definition at line 4471 of file cache_cf.cc.
References Ssl::BumpModeStr, dump_SBufList(), and Acl::Answer::kind.
dump_string()
static void dump_string (StoreEntry * entry, const char * name, char * var) static
Definition at line 2859 of file cache_cf.cc.
References storeAppendPrintf().
dump_time_msec()
static void dump_time_msec (StoreEntry * entry, const char * name, time_msec_t var) static
Definition at line 2956 of file cache_cf.cc.
dump_time_nanoseconds()
static void dump_time_nanoseconds (StoreEntry * entry, const char * name, const std::chrono::nanoseconds & var) static
Definition at line 2978 of file cache_cf.cc.
References storeAppendPrintf().
dump_time_t()
static void dump_time_t (StoreEntry * entry, const char * name, time_t var) static
Definition at line 2933 of file cache_cf.cc.
Referenced by dump_UrlHelperTimeout().
dump_tristate()
static void dump_tristate (StoreEntry * entry, const char * name, int var) static
Definition at line 2595 of file cache_cf.cc.
References storeAppendPrintf().
dump_u_short()
static void dump_u_short (StoreEntry * entry, const char * name, unsigned short var) static
Definition at line 3070 of file cache_cf.cc.
References storeAppendPrintf().
dump_uri_whitespace()
static void dump_uri_whitespace (StoreEntry * entry, const char * name, int var) static
Definition at line 3165 of file cache_cf.cc.
References storeAppendPrintf(), URI_WHITESPACE_ALLOW, URI_WHITESPACE_CHOP, URI_WHITESPACE_DENY, and URI_WHITESPACE_ENCODE.
dump_UrlHelperTimeout()
static void dump_UrlHelperTimeout (StoreEntry * entry, const char * name, SquidConfig::UrlHelperTimeout & config) static
Definition at line 4804 of file cache_cf.cc.
References SquidConfig::UrlHelperTimeout::action, assert, Config, dump_time_t(), SquidConfig::UrlHelperTimeout::response, storeAppendPrintf(), SquidConfig::Timeout, toutActUseConfiguredResponse, and SquidConfig::urlRewrite.
dump_wordlist()
static void dump_wordlist (StoreEntry * entry, const char * name, wordlist * list) static
Definition at line 3107 of file cache_cf.cc.
References wordlist::key, wordlist::next, and storeAppendPrintf().
dump_YesNoNone()
static void dump_YesNoNone (StoreEntry * entry, const char * name, YesNoNone & option) static
Definition at line 3239 of file cache_cf.cc.
References YesNoNone::configured(), and dump_onoff().
DumpDirective()
template<typename T > static void DumpDirective (const T & raw, StoreEntry * entry, const char * name) static
reports raw SquidConfig data member configuration using squid.conf syntax
Parameters
name the name of the configuration directive being dumped
Definition at line 679 of file cache_cf.cc.
References StoreEntry::append(), SBufStream::buf(), Configuration::Component< T >::Print(), and SawDirective().
EvalBoolExpr()
static bool EvalBoolExpr (const char * expr) static
Definition at line 418 of file cache_cf.cc.
References assert, fatalf(), skip_ws(), StrToInt(), trim_trailing_ws(), xfree, xmalloc, and xstrncpy().
Referenced by parseOneConfigFile().
FindStatement()
static const char * FindStatement (const char * line, const char * statement) static
Definition at line 388 of file cache_cf.cc.
References assert, IsSpace(), and skip_ws().
Referenced by parseOneConfigFile().
free_access_log()
static void free_access_log (CustomLog ** definitions) static
Definition at line 4035 of file cache_cf.cc.
References log(), and CustomLog::next.
free_acl()
static void free_acl (Acl::NamedAcls ** config) static
Definition at line 1485 of file cache_cf.cc.
References Acl::FreeNamedAcls().
free_acl_access()
static void free_acl_access (acl_access ** head) static
Definition at line 1512 of file cache_cf.cc.
References aclDestroyAccessList(), and head.
Referenced by free_AuthSchemes(), free_ftp_epsv(), free_on_unsupported_protocol(), and free_sslproxy_ssl_bump().
free_acl_address()
static void free_acl_address (Acl::Address ** head) static
Definition at line 1586 of file cache_cf.cc.
References head.
free_acl_b_size_t()
static void free_acl_b_size_t (AclSizeLimit ** head) static
Definition at line 1728 of file cache_cf.cc.
References head.
free_acl_tos()
static void free_acl_tos (acl_tos ** head) static
Definition at line 1645 of file cache_cf.cc.
References head.
free_address()
static void free_address (Ip::Address * addr) static
Definition at line 1549 of file cache_cf.cc.
References Ip::Address::setEmpty().
free_all()
static void free_all (void) static
Referenced by configFreeMemory().
free_authparam()
static void free_authparam (Auth::ConfigVector * cfg) static
Definition at line 1950 of file cache_cf.cc.
References Auth::Init(), and reconfiguring.
free_AuthSchemes()
static void free_AuthSchemes (acl_access ** authSchemes) static
Definition at line 1983 of file cache_cf.cc.
References free_acl_access(), Auth::Config::schemeLists, and Auth::TheConfig.
free_b_int64_t()
static void free_b_int64_t (int64_t * var) static
Definition at line 3057 of file cache_cf.cc.
free_cache_log_message()
static void free_cache_log_message (DebugMessages ** messages) static
Definition at line 4654 of file cache_cf.cc.
References assert.
free_cachemgrpasswd()
static void free_cachemgrpasswd (Mgr::ActionPasswordList ** head) static
Definition at line 2455 of file cache_cf.cc.
References head.
free_client_delay_pool_count()
static void free_client_delay_pool_count (ClientDelayConfig * cfg) static
Definition at line 1798 of file cache_cf.cc.
References ClientDelayConfig::freePools().
free_configuration_includes_quoted_values()
static void free_configuration_includes_quoted_values (bool * recognizeQuotedValues) static
Definition at line 4850 of file cache_cf.cc.
References ConfigParser::RecognizeQuotedValues, and ConfigParser::StrictMode.
free_CpuAffinityMap()
static void free_CpuAffinityMap (CpuAffinityMap **const cpuAffinityMap) static
Definition at line 4119 of file cache_cf.cc.
free_delay_pool_count()
static void free_delay_pool_count (DelayConfig * cfg) static
Definition at line 1749 of file cache_cf.cc.
References DelayConfig::freePoolCount().
free_denyinfo()
void free_denyinfo (AclDenyInfoList ** var) static
Definition at line 2483 of file cache_cf.cc.
free_ecap_service_type()
static void free_ecap_service_type (Adaptation::Ecap::Config * cfg) static
Definition at line 4193 of file cache_cf.cc.
References Adaptation::Config::freeService().
free_ftp_epsv()
static void free_ftp_epsv (acl_access ** ftp_epsv) static
Definition at line 4721 of file cache_cf.cc.
References free_acl_access(), and FtpEspvDeprecated.
free_HeaderManglers()
static void free_HeaderManglers (HeaderManglers ** pm) static
Definition at line 1859 of file cache_cf.cc.
free_HeaderWithAclList()
static void free_HeaderWithAclList (HeaderWithAclList ** header) static
Definition at line 4533 of file cache_cf.cc.
References aclDestroyAclList().
free_http_upgrade_request_protocols()
static void free_http_upgrade_request_protocols (HttpUpgradeProtocolAccess ** protoGuards) static
Definition at line 4930 of file cache_cf.cc.
References assert.
free_icap_service_failure_limit()
static void free_icap_service_failure_limit (Adaptation::Icap::Config * cfg) static
Definition at line 4233 of file cache_cf.cc.
References Adaptation::Config::oldest_service_failure, and Adaptation::Config::service_failure_limit.
free_icap_service_type()
static void free_icap_service_type (Adaptation::Icap::Config * cfg) static
Definition at line 4155 of file cache_cf.cc.
References Adaptation::Config::freeService().
free_int()
static void free_int (int * var) static
Definition at line 2536 of file cache_cf.cc.
free_int64_t()
static void free_int64_t (int64_t * var) static
Definition at line 2556 of file cache_cf.cc.
free_IpAddress_list()
static void free_IpAddress_list (Ip::Address_list ** head) static
Definition at line 3355 of file cache_cf.cc.
References head.
free_memcachemode()
static void free_memcachemode (SquidConfig *) static
Definition at line 3246 of file cache_cf.cc.
free_note()
static void free_note (Notes * notes) static
Definition at line 4562 of file cache_cf.cc.
References Notes::clean().
free_on_unsupported_protocol()
static void free_on_unsupported_protocol (acl_access ** access) static
Definition at line 4897 of file cache_cf.cc.
References free_acl_access().
free_peer()
static void free_peer (CachePeers **const peers) static
Definition at line 2396 of file cache_cf.cc.
free_refreshpattern()
static void free_refreshpattern (RefreshPattern ** head) static
Definition at line 2847 of file cache_cf.cc.
References head, and refresh_nocache_hack.
free_removalpolicy()
static void free_removalpolicy (RemovalPolicySettings ** settings) static
Definition at line 3184 of file cache_cf.cc.
References free_string(), and free_wordlist.
Referenced by parse_removalpolicy().
free_SBufList()
static void free_SBufList (SBufList * list) static
Definition at line 1464 of file cache_cf.cc.
free_size_t()
static void free_size_t (size_t * var) static
Definition at line 3045 of file cache_cf.cc.
free_ssize_t()
static void free_ssize_t (ssize_t * var) static
Definition at line 3051 of file cache_cf.cc.
free_sslproxy_cert_adapt()
static void free_sslproxy_cert_adapt (sslproxy_cert_adapt ** cert_adapt) static
Definition at line 4305 of file cache_cf.cc.
free_sslproxy_cert_sign()
static void free_sslproxy_cert_sign (sslproxy_cert_sign ** cert_sign) static
Definition at line 4351 of file cache_cf.cc.
free_sslproxy_ssl_bump()
static void free_sslproxy_ssl_bump (acl_access ** ssl_bump) static
Definition at line 4479 of file cache_cf.cc.
References free_acl_access().
free_string()
static void free_string (char ** var) static
Definition at line 2880 of file cache_cf.cc.
References safe_free.
Referenced by free_removalpolicy().
free_time_msec()
static void free_time_msec (time_msec_t * var) static
Definition at line 2972 of file cache_cf.cc.
free_time_nanoseconds()
static void free_time_nanoseconds (std::chrono::nanoseconds * var) static
Definition at line 2991 of file cache_cf.cc.
free_time_t()
static void free_time_t (time_t * var) static
Definition at line 2950 of file cache_cf.cc.
free_u_short()
static void free_u_short (unsigned short * u) static
Definition at line 3076 of file cache_cf.cc.
free_UrlHelperTimeout()
static void free_UrlHelperTimeout (SquidConfig::UrlHelperTimeout * config) static
Definition at line 4819 of file cache_cf.cc.
References SquidConfig::UrlHelperTimeout::action, Config, SquidConfig::UrlHelperTimeout::response, safe_free, SquidConfig::Timeout, and SquidConfig::urlRewrite.
free_YesNoNone()
void free_YesNoNone (YesNoNone *) inline
Definition at line 3227 of file cache_cf.cc.
FreeDirective()
template<typename T > static void FreeDirective (T & raw) static
Definition at line 698 of file cache_cf.cc.
References Configuration::Component< T >::Free().
FromNanoseconds()
template<class TimeUnit > static TimeUnit FromNanoseconds (const std::chrono::nanoseconds & ns, const double parsedValue) static
Definition at line 1187 of file cache_cf.cc.
References TexcHere, and ToSBuf().
GetService()
static unsigned short GetService (const char * proto) static
Parameters
proto 'tcp' or 'udp' for protocol
Returns
Port the named service is supposed to be listening on.
Parses a port number or service name from the squid.conf
Returns either the service port number from /etc/services
Or a numeric translation of the config text.
Definition at line 2110 of file cache_cf.cc.
References isUnsignedNumeric(), ConfigParser::NextToken(), port, self_destruct(), xatos(), and xgetservbyname().
Referenced by GetTcpService(), and GetUdpService().
GetTcpService()
unsigned short GetTcpService (void) inline
Returns
Port the named TCP service is supposed to be listening on.
Parameters
proto 'tcp' or 'udp' for protocol
Returns
Port the named service is supposed to be listening on.
Definition at line 2134 of file cache_cf.cc.
References GetService().
Referenced by parse_peer().
GetUdpService()
unsigned short GetUdpService (void) inline
Returns
Port the named UDP service is supposed to be listening on.
Parameters
proto 'tcp' or 'udp' for protocol
Returns
Port the named service is supposed to be listening on.
Definition at line 2144 of file cache_cf.cc.
References GetService().
Referenced by parse_peer().
IsSpace()
static bool IsSpace (const char ch) static
Determines whether the given squid.conf character is a token-delimiting space character according to squid.conf preprocessor grammar. That grammar only recognizes two space characters: ASCII SP and HT. Unlike isspace(3), this function is not sensitive to locale(1) and does not classify LF, VT, FF, and CR characters as token-delimiting space. However, some squid.conf directive-specific parsers still define space based on isspace(3).
Definition at line 296 of file cache_cf.cc.
References CharacterSet::WSP.
Referenced by FindStatement(), parseOneConfigFile(), skip_ws(), and trim_trailing_ws().
isUnsignedNumeric()
static bool isUnsignedNumeric (const char * str, size_t len) static
utility function to prevent getservbyname() being called with a numeric value on Windows at least it returns garage results.
Definition at line 2094 of file cache_cf.cc.
Referenced by GetService().
parse_access_log()
static void parse_access_log (CustomLog ** logs) static
We support several access_log configuration styles:
#1: Deprecated ancient style without an explicit logging module: access_log /var/log/access.log
#2: The "none" logging module (i.e., no logging [of matching transactions]): access_log none [acl ...]
#3: Configurable logging module without named options: Logformat or the first ACL name, whichever comes first, may not contain '='. If no explicit logformat name is given, the first ACL name, if any, should not be an existing logformat name or it will be treated as such. access_log module:place [logformat_name] [acl ...]
#4: Configurable logging module with name=value options such as logformat=x: The first ACL name may not contain '='. Without any optional parts, directives using this style are indistinguishable from directives using style #1 until we start requiring the "module:" prefix. access_log module:place [option ...] [acl ...]
Definition at line 3963 of file cache_cf.cc.
References aclParseAclList(), assert, Log::Format::CLF_NONE, LegacyParser, CustomLog::next, ConfigParser::NextToken(), ConfigParser::PeekAtToken(), self_destruct(), Log::TheConfig, and xstrdup.
parse_acl()
static void parse_acl (Acl::NamedAcls ** config) static
Definition at line 1478 of file cache_cf.cc.
References assert, LegacyParser, and Acl::Node::ParseNamedAcl().
parse_acl_access()
static void parse_acl_access (acl_access ** head) static
Definition at line 1506 of file cache_cf.cc.
References aclParseAccessLine(), cfg_directive, head, and LegacyParser.
parse_acl_address()
static void parse_acl_address (Acl::Address ** head) static
Definition at line 1572 of file cache_cf.cc.
References Acl::Address::aclList, aclParseAclList(), Acl::Address::addr, head, LegacyParser, Acl::Address::next, and parse_address().
parse_acl_b_size_t()
static void parse_acl_b_size_t (AclSizeLimit ** head) static
Definition at line 1712 of file cache_cf.cc.
References AclSizeLimit::aclList, aclParseAclList(), head, LegacyParser, AclSizeLimit::next, parse_b_int64_t(), and AclSizeLimit::size.
parse_acl_tos()
static void parse_acl_tos (acl_tos ** head) static
Definition at line 1610 of file cache_cf.cc.
References acl_tos::aclList, aclParseAclList(), DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, head, LegacyParser, acl_tos::next, ConfigParser::NextToken(), self_destruct(), acl_tos::tos, and xstrtoui().
parse_adaptation_access_type()
static void parse_adaptation_access_type () static
Definition at line 4140 of file cache_cf.cc.
References LegacyParser, and Adaptation::Config::ParseAccess().
parse_adaptation_service_chain_type()
static void parse_adaptation_service_chain_type () static
Definition at line 4134 of file cache_cf.cc.
References Adaptation::Config::ParseServiceChain().
parse_adaptation_service_set_type()
static void parse_adaptation_service_set_type () static
Definition at line 4128 of file cache_cf.cc.
References Adaptation::Config::ParseServiceSet().
parse_address()
static void parse_address (Ip::Address * addr) static
Definition at line 1525 of file cache_cf.cc.
References DBG_CRITICAL, debugs, Ip::Address::GetHostByName(), ConfigParser::NextToken(), self_destruct(), Ip::Address::setAnyAddr(), and Ip::Address::setNoAddr().
Referenced by parse_acl_address().
parse_authparam()
static void parse_authparam (Auth::ConfigVector * config) static
Definition at line 1910 of file cache_cf.cc.
References DBG_CRITICAL, debugs, Auth::Scheme::Find(), Auth::SchemeConfig::Find(), ConfigParser::NextToken(), Auth::SchemeConfig::parse(), and self_destruct().
parse_AuthSchemes()
static void parse_AuthSchemes (acl_access ** authSchemes) static
Definition at line 1969 of file cache_cf.cc.
References ACCESS_ALLOWED, DBG_CRITICAL, debugs, ConfigParser::LastTokenWasQuoted(), ConfigParser::NextQuotedToken(), ParseAclWithAction(), Auth::Config::schemeLists, self_destruct(), and Auth::TheConfig.
parse_b_int64_t()
static void parse_b_int64_t (int64_t * var) static
Definition at line 3033 of file cache_cf.cc.
References B_BYTES_STR, and parseBytesLine64().
Referenced by parse_acl_b_size_t().
parse_b_size_t()
static void parse_b_size_t (size_t * var) static
Definition at line 3021 of file cache_cf.cc.
References B_BYTES_STR, and parseBytesLine().
parse_b_ssize_t()
static void parse_b_ssize_t (ssize_t * var) static
Definition at line 3027 of file cache_cf.cc.
References B_BYTES_STR, and parseBytesLineSigned().
parse_cache_log_message()
static void parse_cache_log_message (DebugMessages ** messages) static
Definition at line 4575 of file cache_cf.cc.
References assert, Here, DebugMessage::id, DebugMessage::level, DebugMessage::levelled(), DebugMessage::limit, DebugMessage::limited(), ConfigParser::NextKvPair(), ParseDebugMessageId(), ToSBuf(), xatoi(), and xatoull().
parse_cachedir()
static void parse_cachedir (Store::DiskConfig * swap) static
Definition at line 2022 of file cache_cf.cc.
References assert, and Store::Disks::Parse().
parse_cachemgrpasswd()
static void parse_cachemgrpasswd (Mgr::ActionPasswordList ** head) static
Definition at line 2420 of file cache_cf.cc.
References Mgr::ActionPasswordList::actions, config_lineno, DBG_PARSE_NOTE, debugs, head, Mgr::ActionPasswordList::next, ConfigParser::NextQuotedToken(), parse_string(), and Mgr::ActionPasswordList::passwd.
parse_client_delay_pool_access()
static void parse_client_delay_pool_access (ClientDelayConfig * cfg) static
Definition at line 1822 of file cache_cf.cc.
References LegacyParser, and ClientDelayConfig::parsePoolAccess().
parse_client_delay_pool_count()
static void parse_client_delay_pool_count (ClientDelayConfig * cfg) static
Definition at line 1810 of file cache_cf.cc.
References ClientDelayConfig::parsePoolCount().
parse_client_delay_pool_rates()
static void parse_client_delay_pool_rates (ClientDelayConfig * cfg) static
Definition at line 1816 of file cache_cf.cc.
References ClientDelayConfig::parsePoolRates().
parse_configuration_includes_quoted_values()
static void parse_configuration_includes_quoted_values (bool * recognizeQuotedValues) static
Definition at line 4827 of file cache_cf.cc.
References parse_onoff(), ConfigParser::RecognizeQuotedValues, and ConfigParser::StrictMode.
parse_CpuAffinityMap()
static void parse_CpuAffinityMap (CpuAffinityMap **const cpuAffinityMap) static
Definition at line 4068 of file cache_cf.cc.
References DBG_CRITICAL, debugs, ConfigParser::NextToken(), and self_destruct().
parse_delay_pool_access()
static void parse_delay_pool_access (DelayConfig * cfg) static
Definition at line 1779 of file cache_cf.cc.
References LegacyParser, and DelayConfig::parsePoolAccess().
parse_delay_pool_class()
static void parse_delay_pool_class (DelayConfig * cfg) static
Definition at line 1767 of file cache_cf.cc.
References DelayConfig::parsePoolClass().
parse_delay_pool_count()
static void parse_delay_pool_count (DelayConfig * cfg) static
Definition at line 1761 of file cache_cf.cc.
References DelayConfig::parsePoolCount().
parse_delay_pool_rates()
static void parse_delay_pool_rates (DelayConfig * cfg) static
Definition at line 1773 of file cache_cf.cc.
References DelayConfig::parsePoolRates().
parse_denyinfo()
static void parse_denyinfo (AclDenyInfoList ** var) static
Definition at line 2477 of file cache_cf.cc.
References aclParseDenyInfoLine().
parse_ecap_service_type()
static void parse_ecap_service_type (Adaptation::Ecap::Config * cfg) static
Definition at line 4187 of file cache_cf.cc.
References Adaptation::Config::parseService().
parse_eol()
void parse_eol (char *volatile * var)
Definition at line 2886 of file cache_cf.cc.
References ConfigParser::NextQuotedOrToEol(), safe_free, self_destruct(), xisspace, and xstrdup.
parse_ftp_epsv()
static void parse_ftp_epsv (acl_access ** ftp_epsv) static
Definition at line 4663 of file cache_cf.cc.
References ACCESS_ALLOWED, ACCESS_DENIED, aclParseAccessLine(), cfg_directive, DBG_CRITICAL, debugs, Acl::Node::FindByName(), FtpEspvDeprecated, LegacyParser, ConfigParser::NextToken(), ParseAclWithAction(), ConfigParser::PeekAtToken(), and self_destruct().
parse_HeaderWithAclList()
static void parse_HeaderWithAclList (HeaderWithAclList ** header) static
Definition at line 4499 of file cache_cf.cc.
References HeaderWithAcl::aclList, aclParseAclList(), Http::BAD_HDR, ConfigParser::DisableMacros(), ConfigParser::EnableMacros(), HeaderWithAcl::fieldId, HeaderWithAcl::fieldName, HeaderWithAcl::fieldValue, Http::HeaderLookupTable, Http::HeaderTableRecord::id, ConfigParser::LastTokenWasQuoted(), LegacyParser, Http::HeaderLookupTable_t::lookup(), ConfigParser::NextQuotedToken(), ConfigParser::NextToken(), Http::OTHER, Format::Format::parse(), HeaderWithAcl::quoted, self_destruct(), String::termedBuf(), and HeaderWithAcl::valueFormat.
parse_hostdomaintype()
static void parse_hostdomaintype (void) static
Definition at line 2499 of file cache_cf.cc.
References ConfigParser::cachePeer(), LegacyParser, ConfigParser::NextToken(), parseNeighborType(), self_destruct(), xcalloc(), and xstrdup.
parse_http_header_access()
static void parse_http_header_access (HeaderManglers ** manglers) static
Definition at line 1837 of file cache_cf.cc.
References headerMangler::access_list, aclParseAccessLine(), assert, cfg_filename, config_input_line, config_lineno, DBG_CRITICAL, debugs, LegacyParser, ConfigParser::NextToken(), and HeaderManglers::track().
parse_http_header_replace()
static void parse_http_header_replace (HeaderManglers ** manglers) static
Definition at line 1876 of file cache_cf.cc.
References cfg_filename, config_input_line, config_lineno, DBG_CRITICAL, debugs, ConfigParser::NextQuotedOrToEol(), ConfigParser::NextToken(), and HeaderManglers::setReplacement().
parse_http_upgrade_request_protocols()
static void parse_http_upgrade_request_protocols (HttpUpgradeProtocolAccess ** protoGuards) static
Definition at line 4903 of file cache_cf.cc.
References assert, and LegacyParser.
parse_icap_access_type()
static void parse_icap_access_type () static
Definition at line 4175 of file cache_cf.cc.
References DBG_CRITICAL, debugs, LegacyParser, and Adaptation::Config::ParseAccess().
parse_icap_class_type()
static void parse_icap_class_type () static
Definition at line 4167 of file cache_cf.cc.
References DBG_CRITICAL, debugs, and Adaptation::Config::ParseServiceSet().
parse_icap_service_failure_limit()
static void parse_icap_service_failure_limit (Adaptation::Icap::Config * cfg) static
Definition at line 4207 of file cache_cf.cc.
References config_input_line, DBG_CRITICAL, debugs, GetInteger(), ConfigParser::NextToken(), Adaptation::Config::oldest_service_failure, parse_time_t(), self_destruct(), and Adaptation::Config::service_failure_limit.
parse_icap_service_type()
static void parse_icap_service_type (Adaptation::Icap::Config * cfg) static
Definition at line 4149 of file cache_cf.cc.
References Adaptation::Config::parseService().
parse_int()
void parse_int (int * var)
Definition at line 2528 of file cache_cf.cc.
References GetInteger().
Referenced by parse_obsolete(), and parse_pipelinePrefetch().
parse_int64_t()
static void parse_int64_t (int64_t * var) static
Definition at line 2548 of file cache_cf.cc.
References GetInteger64().
parse_IpAddress_list()
static void parse_IpAddress_list (Ip::Address_list ** head) static
Definition at line 3318 of file cache_cf.cc.
References GetHostWithPort(), head, squidaio_request_t::next, ConfigParser::NextToken(), Ip::Address_list::s, self_destruct(), and xcalloc().
parse_kb_int64_t()
static void parse_kb_int64_t (int64_t * var) static
Definition at line 3039 of file cache_cf.cc.
References B_KBYTES_STR, and parseBytesLine64().
parse_line()
static int parse_line (char *) static
Referenced by sslBumpCfgRr::finalizeConfig(), and parseOneConfigFile().
parse_memcachemode()
static void parse_memcachemode (SquidConfig *) static
Definition at line 3250 of file cache_cf.cc.
References Config, DBG_PARSE_NOTE, debugs, SquidConfig::memory_cache_disk, SquidConfig::memory_cache_first, ConfigParser::NextToken(), SquidConfig::onoff, and self_destruct().
parse_note()
static void parse_note (Notes * notes) static
Definition at line 4551 of file cache_cf.cc.
References assert, LegacyParser, and Notes::parse().
parse_obsolete()
void parse_obsolete (const char * name) static
Parse a line containing an obsolete directive. To upgrade it where possible instead of just "Bungled config" for directives which cannot be marked as simply aliases of the some name. For example if the parameter order and content has changed. Or if the directive has been completely removed.
Definition at line 1054 of file cache_cf.cc.
References SBuf::append(), SBuf::c_str(), SquidConfig::cache_miss_revalidate, Helper::ChildConfig::concurrency, Config, DBG_CRITICAL, debugs, Here, ConfigParser::NextQuotedOrToEol(), SquidConfig::onoff, Security::PeerOptions::parse(), parse_int(), parse_onoff(), Security::ProxyOutgoingConfig(), SquidConfig::redirectChildren, self_destruct(), and ToSBuf().
parse_on_unsupported_protocol()
static void parse_on_unsupported_protocol (acl_access ** access) static
Definition at line 4857 of file cache_cf.cc.
References ACCESS_ALLOWED, DBG_CRITICAL, debugs, ConfigParser::NextToken(), ParseAclWithAction(), and self_destruct().
parse_onoff()
void parse_onoff (int * var)
Definition at line 2568 of file cache_cf.cc.
References DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, ConfigParser::NextToken(), and self_destruct().
Referenced by Auth::SchemeConfig::parse(), parse_configuration_includes_quoted_values(), parse_obsolete(), and parse_YesNoNone().
parse_peer()
static void parse_peer (CachePeers ** peers) static
Definition at line 2150 of file cache_cf.cc.
References CachePeers::add(), DBG_CRITICAL, DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, fatalf(), findCachePeerByName(), GetTcpService(), GetUdpService(), Here, ConfigParser::NextToken(), parseNeighborType(), PEER_MULTICAST, PEER_PARENT, peerClearRRStart(), rfc1738_unescape(), safe_free, self_destruct(), ToSBuf(), xatoi(), and xstrdup.
parse_peer_access()
static void parse_peer_access (void) static
Definition at line 2490 of file cache_cf.cc.
References aclParseAccessLine(), ConfigParser::cachePeer(), LegacyParser, and CachePeer::name.
parse_pipelinePrefetch()
static void parse_pipelinePrefetch (int * var) static
Definition at line 2639 of file cache_cf.cc.
References DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, ConfigParser::NextToken(), parse_int(), ConfigParser::PeekAtToken(), and self_destruct().
parse_port_option()
static void parse_port_option (AnyP::PortCfgPointer & s, char * token) static
Definition at line 3478 of file cache_cf.cc.
References cfg_directive, DBG_CRITICAL, DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, DISABLE_PMTU_ALWAYS, DISABLE_PMTU_OFF, DISABLE_PMTU_TRANSPARENT, parsePortProtocol(), safe_free, self_destruct(), TexcHere, ToSBuf(), ToUpper(), xatos(), xatoui(), and xstrdup.
Referenced by parsePortCfg().
parse_refreshpattern()
static void parse_refreshpattern (RefreshPattern ** head) static
Definition at line 2709 of file cache_cf.cc.
References DBG_CRITICAL, DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, RefreshPattern::flags, GetInteger(), GetPercentage(), head, RefreshPattern::ignore_no_store, RefreshPattern::ignore_private, RefreshPattern::ignore_reload, LegacyParser, max(), RefreshPattern::max, RefreshPattern::max_stale, min(), RefreshPattern::min, squidaio_request_t::next, RefreshPattern::next, ConfigParser::NextToken(), RefreshPattern::override_expire, RefreshPattern::override_lastmod, RefreshPattern::pct, RefreshPattern::refresh_ims, refresh_nocache_hack, ConfigParser::regex(), RefreshPattern::reload_into_ims, RefreshPattern::store_stale, and xatoi().
parse_removalpolicy()
static void parse_removalpolicy (RemovalPolicySettings ** settings) static
Definition at line 3199 of file cache_cf.cc.
References free_removalpolicy(), parse_string(), and parse_wordlist().
parse_SBufList()
static void parse_SBufList (SBufList * list) static
Definition at line 1435 of file cache_cf.cc.
References ConfigParser::NextQuotedToken().
parse_sslproxy_cert_adapt()
static void parse_sslproxy_cert_adapt (sslproxy_cert_adapt ** cert_adapt) static
Definition at line 4241 of file cache_cf.cc.
References aclParseAclList(), Ssl::algSetCommonName, Ssl::algSetValidAfter, Ssl::algSetValidBefore, Ssl::CertAdaptAlgorithmStr, DBG_CRITICAL, debugs, LegacyParser, sslproxy_cert_adapt::next, ConfigParser::NextToken(), self_destruct(), and xstrdup.
parse_sslproxy_cert_sign()
static void parse_sslproxy_cert_sign (sslproxy_cert_sign ** cert_sign) static
Definition at line 4311 of file cache_cf.cc.
References aclParseAclList(), Ssl::algSignSelf, Ssl::algSignTrusted, Ssl::algSignUntrusted, Ssl::CertSignAlgorithmStr, DBG_CRITICAL, debugs, LegacyParser, sslproxy_cert_sign::next, ConfigParser::NextToken(), and self_destruct().
parse_sslproxy_ssl_bump()
static void parse_sslproxy_ssl_bump (acl_access ** ssl_bump) static
Definition at line 4391 of file cache_cf.cc.
References ACCESS_ALLOWED, Ssl::bumpBump, Ssl::bumpClientFirst, Ssl::bumpEnd, Ssl::BumpModeStr, Ssl::bumpNone, Ssl::bumpPeek, Ssl::bumpServerFirst, Ssl::bumpSplice, Ssl::bumpStare, Ssl::bumpTerminate, DBG_CRITICAL, debugs, sslBumpCfgRr::lastDeprecatedRule, ConfigParser::NextToken(), ParseAclWithAction(), and self_destruct().
parse_string()
static void parse_string (char ** var) static
Definition at line 2866 of file cache_cf.cc.
References ConfigParser::NextToken(), safe_free, self_destruct(), and xstrdup.
Referenced by parse_cachemgrpasswd(), and parse_removalpolicy().
parse_time_msec()
static void parse_time_msec (time_msec_t * var) static
Definition at line 2966 of file cache_cf.cc.
parse_time_nanoseconds()
static void parse_time_nanoseconds (std::chrono::nanoseconds * var) static
Definition at line 2985 of file cache_cf.cc.
parse_time_t()
void parse_time_t (time_t * var)
Definition at line 2940 of file cache_cf.cc.
References TexcHere, and ToSBuf().
Referenced by parse_icap_service_failure_limit().
parse_TokenOrQuotedString()
static void parse_TokenOrQuotedString (char ** var) static
Definition at line 2916 of file cache_cf.cc.
References ConfigParser::NextQuotedToken(), safe_free, self_destruct(), and xstrdup.
parse_tristate()
static void parse_tristate (int * var) static
Definition at line 2610 of file cache_cf.cc.
References DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, ConfigParser::NextToken(), and self_destruct().
parse_u_short()
static void parse_u_short (unsigned short * var) static
Definition at line 3082 of file cache_cf.cc.
References ConfigParser::ParseUShort().
parse_uri_whitespace()
static void parse_uri_whitespace (int * var) static
Definition at line 3140 of file cache_cf.cc.
References DBG_PARSE_NOTE, debugs, ConfigParser::NextToken(), self_destruct(), URI_WHITESPACE_ALLOW, URI_WHITESPACE_CHOP, URI_WHITESPACE_DENY, URI_WHITESPACE_ENCODE, and URI_WHITESPACE_STRIP.
parse_UrlHelperTimeout()
static void parse_UrlHelperTimeout (SquidConfig::UrlHelperTimeout * config) static
Definition at line 4761 of file cache_cf.cc.
References SquidConfig::UrlHelperTimeout::action, Config, DBG_CRITICAL, debugs, ConfigParser::NextKvPair(), ParseUrlRewriteTimeout(), SquidConfig::UrlHelperTimeout::response, self_destruct(), SquidConfig::Timeout, toutActBypass, toutActFail, toutActRetry, toutActUseConfiguredResponse, SquidConfig::urlRewrite, and xstrdup.
parse_wordlist()
void parse_wordlist (wordlist ** list)
Definition at line 3122 of file cache_cf.cc.
References ConfigParser::NextQuotedToken(), and wordlistAdd().
Referenced by Auth::SchemeConfig::parse(), parse_externalAclHelper(), parse_removalpolicy(), and ConfigParser::ParseWordList().
parse_YesNoNone()
static void parse_YesNoNone (YesNoNone * option) static
Definition at line 3231 of file cache_cf.cc.
References YesNoNone::configure(), and parse_onoff().
ParseAclWithAction()
static void ParseAclWithAction (acl_access ** access, const Acl::Answer & action, const char * desc, Acl::Node * acl = nullptr) static
Definition at line 2001 of file cache_cf.cc.
References Acl::InnerNode::add(), assert, config_input_line, Acl::Node::context(), Acl::InnerNode::lineParse(), and ToSBuf().
Referenced by parse_AuthSchemes(), parse_ftp_epsv(), parse_on_unsupported_protocol(), and parse_sslproxy_ssl_bump().
parseBytesLine()
static void parseBytesLine (size_t * bptr, const char * units) static
Definition at line 1284 of file cache_cf.cc.
References config_input_line, DBG_CRITICAL, debugs, ConfigParser::NextToken(), parseBytesUnits(), self_destruct(), and xatof().
Referenced by parse_b_size_t().
parseBytesLine64()
static void parseBytesLine64 (int64_t * bptr, const char * units) static
Definition at line 1237 of file cache_cf.cc.
References config_input_line, DBG_CRITICAL, debugs, ConfigParser::NextToken(), parseBytesUnits(), self_destruct(), and xatof().
Referenced by parse_b_int64_t(), and parse_kb_int64_t().
parseBytesLineSigned()
static void parseBytesLineSigned (ssize_t * bptr, const char * units) static
Definition at line 1331 of file cache_cf.cc.
References config_input_line, DBG_CRITICAL, debugs, ConfigParser::NextToken(), parseBytesUnits(), self_destruct(), and xatof().
Referenced by parse_b_ssize_t().
parseBytesOptionValue()
void parseBytesOptionValue (size_t * bptr, const char * units, char const * value)
Parse bytes from a string. Similar to the parseBytesLine function but parses the string value instead of the current token value.
Definition at line 1383 of file cache_cf.cc.
References String::assign(), parseBytesUnits(), self_destruct(), and xatoi().
Referenced by Security::ServerOptions::parse(), and FormattedLog::parseOptions().
parseBytesUnits()
static size_t parseBytesUnits (const char * unit) static
Definition at line 1415 of file cache_cf.cc.
References B_BYTES_STR, B_GBYTES_STR, B_KBYTES_STR, B_MBYTES_STR, DBG_CRITICAL, and debugs.
Referenced by parseBytesLine(), parseBytesLine64(), parseBytesLineSigned(), and parseBytesOptionValue().
ParseDebugMessageId()
static DebugMessageId ParseDebugMessageId (const char * value, const char eov) static
Definition at line 4567 of file cache_cf.cc.
References DebugMessageIdUpperBound, Here, ToSBuf(), and xatoui().
Referenced by parse_cache_log_message().
ParseDirective()
template<typename T > static void ParseDirective (T & raw, ConfigParser & parser) static
Sets the given raw SquidConfig data member. Extracts and interprets parser's configuration tokens.
Definition at line 663 of file cache_cf.cc.
References ConfigParser::closeDirective(), Must, Configuration::Component< T >::Parse(), ConfigParser::rejectDuplicateDirective(), and SawDirective().
parseManyConfigFiles()
static int parseManyConfigFiles (char * files, int depth) static
Definition at line 311 of file cache_cf.cc.
References fatalf(), int, NULL, parseOneConfigFile(), strwordtok(), and xstrerr().
Referenced by parseOneConfigFile().
parseNeighborType()
peer_t parseNeighborType (const char * s) static
Definition at line 3294 of file cache_cf.cc.
References DBG_CRITICAL, debugs, PEER_MULTICAST, PEER_PARENT, and PEER_SIBLING.
Referenced by parse_hostdomaintype(), and parse_peer().
parseOneConfigFile()
static int parseOneConfigFile (const char * file_name, unsigned int depth) static
Definition at line 446 of file cache_cf.cc.
References BUFSIZ, cfg_filename, config_input_line, config_lineno, CurrentException(), ConfigParser::CurrentLocation(), DBG_CRITICAL, debugs, EvalBoolExpr(), Debug::Extra(), fatalf(), FindStatement(), Important, IsSpace(), O_TEXT, opt_parse_cfg_only, parse_line(), parseManyConfigFiles(), ProcessMacros(), safe_free, self_destruct(), SetConfigFilename(), skip_ws(), trim_trailing_ws(), xfree, xrealloc(), xstrerr(), and xstrncpy().
Referenced by Configuration::Parse(), and parseManyConfigFiles().
parsePortCfg()
static void parsePortCfg (AnyP::PortCfgPointer * head, const char * protocol) static
Definition at line 3710 of file cache_cf.cc.
References SBuf::cmp(), DBG_CRITICAL, debugs, head, IPV6_SPECIAL_SPLITSTACK, SBuf::isEmpty(), ConfigParser::NextToken(), parse_port_option(), parsePortProtocol(), parsePortSpecification(), AnyP::PROTO_HTTPS, and self_destruct().
parsePortProtocol()
static AnyP::ProtocolVersion parsePortProtocol (const SBuf & value) static
parses the protocol= option of the *_port directive, returning parsed value unsupported option values result in a fatal error message upper case values required; caller may convert for backward compatibility
Definition at line 3460 of file cache_cf.cc.
References cfg_directive, SBuf::cmp(), fatalf(), AnyP::PROTO_HTTPS, Ftp::ProtocolVersion(), Http::ProtocolVersion(), SQUIDSBUFPH, and SQUIDSBUFPRINT.
Referenced by add_http_port(), parse_port_option(), and parsePortCfg().
parsePortSpecification()
static void parsePortSpecification (const AnyP::PortCfgPointer & s, char * token) static
Definition at line 3375 of file cache_cf.cc.
References DBG_CRITICAL, debugs, DISABLE_PMTU_OFF, AnyP::UriScheme::image(), port, self_destruct(), xatos(), and xstrdup.
Referenced by add_http_port(), and parsePortCfg().
parseTimeLine()
template<class TimeUnit > static TimeUnit parseTimeLine () static
Parses a time specification from the config file and returns the time as a chrono duration object of 'TimeUnit' type.
Definition at line 1202 of file cache_cf.cc.
References ConfigParser::CurrentLocation(), DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, ConfigParser::NextToken(), ConfigParser::PeekAtToken(), TexcHere, ToNanoSeconds(), ToSBuf(), and xatof().
parseTimeUnit()
template<class MinimalUnit > static bool parseTimeUnit (const char * unitName, std::chrono::nanoseconds & ns) static
Assigns 'ns' the number of nanoseconds corresponding to 'unitName'.
Parameters
MinimalUnit is a chrono duration type specifying the minimal allowed time unit.
Returns
true if unitName is correct and its time unit is not less than MinimalUnit.
Definition at line 1131 of file cache_cf.cc.
References HoursPerYear, T_DAY_STR, T_DECADE_STR, T_FORTNIGHT_STR, T_HOUR_STR, T_MICROSECOND_STR, T_MILLISECOND_STR, T_MINUTE_STR, T_MONTH_STR, T_NANOSECOND_STR, T_SECOND_STR, T_WEEK_STR, T_YEAR_STR, TexcHere, and ToSBuf().
ParseUrlRewriteTimeout()
static std::chrono::seconds ParseUrlRewriteTimeout () static
Like parseTimeLine() but does not require the timeunit to be specified. If missed, the default 'second' timeunit is assumed.
Definition at line 4730 of file cache_cf.cc.
References assert, ConfigParser::CurrentLocation(), DBG_IMPORTANT, DBG_PARSE_NOTE, debugs, ConfigParser::NextToken(), ConfigParser::PeekAtToken(), T_SECOND_STR, TexcHere, ToNanoSeconds(), and xatof().
Referenced by parse_UrlHelperTimeout().
peer_type_str()
static const char * peer_type_str (const peer_t type) static
Definition at line 2029 of file cache_cf.cc.
References PEER_MULTICAST, PEER_PARENT, and PEER_SIBLING.
Referenced by dump_peer().
ProcessMacros()
static void ProcessMacros (char *& line, int & len) static
Definition at line 370 of file cache_cf.cc.
References SBuf::c_str(), KidIdentifier, service_name, SubstituteMacro(), TheKidName, and xitoa().
Referenced by parseOneConfigFile().
ReplaceSubstr()
static void ReplaceSubstr (char *& str, int & len, unsigned substrIdx, unsigned substrLen, const char * newSubstr) static
Definition at line 341 of file cache_cf.cc.
References assert.
Referenced by SubstituteMacro().
requirePathnameExists()
void requirePathnameExists (const char * name, const char * path)
Definition at line 3914 of file cache_cf.cc.
References assert, BUFSIZ, SquidConfig::chroot_dir, Config, DBG_CRITICAL, debugs, fatalf(), opt_parse_cfg_only, opt_send_signal, and xstrerr().
Referenced by configDoConfigure(), ipcCreate(), and Auth::SchemeConfig::parse().
SawDirective()
template<typename T > static bool SawDirective (const T & raw) static
Definition at line 654 of file cache_cf.cc.
Referenced by DumpDirective(), and ParseDirective().
self_destruct()
void self_destruct (void)
Definition at line 275 of file cache_cf.cc.
References ConfigParser::destruct(), and LegacyParser.
Referenced by ErrorDynamicPageInfo::ErrorDynamicPageInfo(), configDoConfigure(), dump_wccp2_amethod(), dump_wccp2_method(), acl_ip_data::FactoryParse(), GetInteger(), GetInteger64(), GetPercentage(), GetService(), GetShort(), Acl::InnerNode::lineParse(), ConfigParser::NextToken(), Fs::Ufs::UFSSwapDir::optionIOParse(), Store::Disk::optionObjectSizeParse(), DelaySpec::parse(), IcmpConfig::parse(), ACLAdaptationServiceData::parse(), ACLAnnotationData::parse(), ACLCertificateData::parse(), ACLHasComponentData::parse(), ACLIntRange::parse(), ACLSquidErrorData::parse(), ACLTimeData::parse(), ACLExternal::parse(), Security::ServerOptions::parse(), Auth::SchemeConfig::parse(), parse_access_log(), parse_acl_tos(), parse_address(), parse_authparam(), parse_AuthSchemes(), parse_CpuAffinityMap(), parse_eol(), parse_externalAclHelper(), parse_ftp_epsv(), parse_HeaderWithAclList(), parse_hostdomaintype(), parse_icap_service_failure_limit(), parse_IpAddress_list(), parse_memcachemode(), parse_obsolete(), parse_on_unsupported_protocol(), parse_onoff(), parse_peer(), parse_pipelinePrefetch(), parse_port_option(), parse_sslproxy_cert_adapt(), parse_sslproxy_cert_sign(), parse_sslproxy_ssl_bump(), parse_string(), parse_TokenOrQuotedString(), parse_tristate(), parse_uri_whitespace(), parse_UrlHelperTimeout(), parse_wccp2_amethod(), parse_wccp2_method(), parse_wccp2_service(), parse_wccp2_service_info(), ConfigParser::ParseBool(), parseBytesLine(), parseBytesLine64(), parseBytesLineSigned(), parseBytesOptionValue(), ACLHasComponentData::parseComponent(), Helper::ChildConfig::parseConfig(), Log::LogConfig::parseFormats(), XactionInitiator::ParseInitiators(), parseOneConfigFile(), Store::Disk::parseOptions(), parsePortCfg(), parsePortSpecification(), Rock::SwapDir::parseRateOption(), MessageDelayConfig::parseResponseDelayPool(), Rock::SwapDir::parseSizeOption(), Rock::SwapDir::parseTimeOption(), ConfigParser::RegexStrtokFile(), ConfigParser::TokenParse(), ConfigParser::UnQuote(), xatof(), xatoi(), xatol(), xatoll(), and xatos().
SetConfigFilename()
static void SetConfigFilename (char const * file_name, bool is_pipe) static
Definition at line 281 of file cache_cf.cc.
References cfg_filename.
Referenced by parseOneConfigFile().
skip_ws()
static const char * skip_ws (const char * s) static
Definition at line 302 of file cache_cf.cc.
References IsSpace().
Referenced by EvalBoolExpr(), FindStatement(), and parseOneConfigFile().
StrToInt()
static bool StrToInt (const char * str, long & number) static
Definition at line 407 of file cache_cf.cc.
References assert.
Referenced by EvalBoolExpr().
SubstituteMacro()
static void SubstituteMacro (char *& line, int & len, const char * macroName, const char * substStr) static
Definition at line 359 of file cache_cf.cc.
References assert, and ReplaceSubstr().
Referenced by ProcessMacros().
TimeUnitToString()
template<class MinimalUnit > static const char * TimeUnitToString () static
Definition at line 1109 of file cache_cf.cc.
References assert, T_MICROSECOND_STR, T_MILLISECOND_STR, T_NANOSECOND_STR, and T_SECOND_STR.
ToNanoSeconds()
static std::chrono::nanoseconds ToNanoSeconds (const double value, const std::chrono::nanoseconds & unit) static
Definition at line 1172 of file cache_cf.cc.
References HoursPerYear, TexcHere, and ToSBuf().
Referenced by parseTimeLine(), and ParseUrlRewriteTimeout().
trim_trailing_ws()
static void trim_trailing_ws (char * str) static
Definition at line 378 of file cache_cf.cc.
References assert, and IsSpace().
Referenced by EvalBoolExpr(), and parseOneConfigFile().
Variable Documentation
B_BYTES_STR
const char* const B_BYTES_STR = "bytes" static
Definition at line 156 of file cache_cf.cc.
Referenced by dump_acl_b_size_t(), dump_b_int64_t(), dump_b_size_t(), dump_b_ssize_t(), parse_b_int64_t(), parse_b_size_t(), parse_b_ssize_t(), and parseBytesUnits().
B_GBYTES_STR
const char* const B_GBYTES_STR = "GB" static
Definition at line 159 of file cache_cf.cc.
Referenced by parseBytesUnits().
B_KBYTES_STR
const char* const B_KBYTES_STR = "KB" static
Definition at line 157 of file cache_cf.cc.
Referenced by dump_kb_int64_t(), parse_kb_int64_t(), and parseBytesUnits().
B_MBYTES_STR
const char* const B_MBYTES_STR = "MB" static
Definition at line 158 of file cache_cf.cc.
Referenced by parseBytesUnits().
cfg_directive
const char* cfg_directive = nullptr
Definition at line 269 of file cache_cf.cc.
Referenced by aclParseAclList(), ConfigParser::closeDirective(), HttpUpgradeProtocolAccess::configureGuard(), ConfigParser::CurrentLocation(), ConfigParser::optionalAclList(), parse_acl_access(), parse_ftp_epsv(), parse_port_option(), FormattedLog::parseOptions(), parsePortProtocol(), ConfigParser::rejectDuplicateDirective(), and FormattedLog::setLogformat().
cfg_filename
const char* cfg_filename = nullptr
Definition at line 270 of file cache_cf.cc.
Referenced by aclParseAccessLine(), aclParseArpData(), aclParseDenyInfoLine(), aclParseEuiData(), compileOptimisedREs(), ConfigParser::CurrentLocation(), ConfigParser::destruct(), Adaptation::ServiceConfig::grokBool(), Adaptation::ServiceConfig::grokExtension(), Adaptation::ServiceConfig::grokLong(), Adaptation::ServiceConfig::grokOnOverload(), Adaptation::ServiceConfig::grokUri(), Adaptation::ServiceConfig::parse(), ACLRegexData::parse(), ACLTimeData::parse(), parse_http_header_access(), parse_http_header_replace(), Log::LogConfig::parseFormats(), parseOneConfigFile(), Adaptation::Config::parseService(), removeUnnecessaryWildcards(), and SetConfigFilename().
config_input_line
char config_input_line[BUFSIZ] = {}
Definition at line 272 of file cache_cf.cc.
Referenced by aclParseAccessLine(), aclParseAclList(), aclParseArpData(), aclParseDenyInfoLine(), aclParseEuiData(), compileOptimisedREs(), ConfigParser::destruct(), Acl::InnerNode::lineParse(), Acl::AllOf::parse(), ACLRegexData::parse(), ACLTimeData::parse(), parse_http_header_access(), parse_http_header_replace(), parse_icap_service_failure_limit(), ParseAclWithAction(), parseBytesLine(), parseBytesLine64(), parseBytesLineSigned(), Acl::Node::ParseNamed(), parseOneConfigFile(), and removeUnnecessaryWildcards().
config_lineno
int config_lineno = 0
Definition at line 271 of file cache_cf.cc.
Referenced by aclParseAccessLine(), aclParseArpData(), aclParseDenyInfoLine(), aclParseEuiData(), compileOptimisedREs(), ConfigParser::CurrentLocation(), ConfigParser::destruct(), Adaptation::ServiceConfig::grokBool(), Adaptation::ServiceConfig::grokExtension(), Adaptation::ServiceConfig::grokLong(), Adaptation::ServiceConfig::grokOnOverload(), Adaptation::ServiceConfig::grokUri(), Adaptation::ServiceConfig::parse(), ACLRegexData::parse(), ACLTimeData::parse(), parse_cachemgrpasswd(), parse_http_header_access(), parse_http_header_replace(), Log::LogConfig::parseFormats(), parseOneConfigFile(), Adaptation::Config::parseService(), and removeUnnecessaryWildcards().
dump_config
OBJH dump_config static
Definition at line 187 of file cache_cf.cc.
Referenced by Configuration::Parse().
FtpEspvDeprecated
bool FtpEspvDeprecated = false static
Definition at line 4662 of file cache_cf.cc.
Referenced by free_ftp_epsv(), and parse_ftp_epsv().
HoursPerYear
const double HoursPerYear = 24*365.2522 static
Definition at line 162 of file cache_cf.cc.
Referenced by parseTimeUnit(), and ToNanoSeconds().
LegacyParser
ConfigParser LegacyParser = ConfigParser() static
Definition at line 267 of file cache_cf.cc.
Referenced by parse_access_log(), parse_acl(), parse_acl_access(), parse_acl_address(), parse_acl_b_size_t(), parse_acl_tos(), parse_adaptation_access_type(), parse_client_delay_pool_access(), parse_delay_pool_access(), parse_ftp_epsv(), parse_HeaderWithAclList(), parse_hostdomaintype(), parse_http_header_access(), parse_http_upgrade_request_protocols(), parse_icap_access_type(), parse_note(), parse_peer_access(), parse_refreshpattern(), parse_sslproxy_cert_adapt(), parse_sslproxy_cert_sign(), self_destruct(), and TestACLMaxUserIP::testParseLine().
T_DAY_STR
const char* const T_DAY_STR = "day" static
Definition at line 149 of file cache_cf.cc.
Referenced by parseTimeUnit().
T_DECADE_STR
const char* const T_DECADE_STR = "decade" static
Definition at line 154 of file cache_cf.cc.
Referenced by parseTimeUnit().
T_FORTNIGHT_STR
const char* const T_FORTNIGHT_STR = "fortnight" static
Definition at line 151 of file cache_cf.cc.
Referenced by parseTimeUnit().
T_HOUR_STR
const char* const T_HOUR_STR = "hour" static
Definition at line 148 of file cache_cf.cc.
Referenced by parseTimeUnit().
T_MICROSECOND_STR
const char* const T_MICROSECOND_STR = "microsecond" static
Definition at line 144 of file cache_cf.cc.
Referenced by parseTimeUnit(), and TimeUnitToString().
T_MILLISECOND_STR
const char* const T_MILLISECOND_STR = "millisecond" static
Definition at line 145 of file cache_cf.cc.
Referenced by parseTimeUnit(), and TimeUnitToString().
T_MINUTE_STR
const char* const T_MINUTE_STR = "minute" static
Definition at line 147 of file cache_cf.cc.
Referenced by parseTimeUnit().
T_MONTH_STR
const char* const T_MONTH_STR = "month" static
Definition at line 152 of file cache_cf.cc.
Referenced by parseTimeUnit().
T_NANOSECOND_STR
const char* const T_NANOSECOND_STR = "nanosecond" static
Definition at line 143 of file cache_cf.cc.
Referenced by parseTimeUnit(), and TimeUnitToString().
T_SECOND_STR
const char* const T_SECOND_STR = "second" static
Definition at line 146 of file cache_cf.cc.
Referenced by parseTimeUnit(), ParseUrlRewriteTimeout(), and TimeUnitToString().
T_WEEK_STR
const char* const T_WEEK_STR = "week" static
Definition at line 150 of file cache_cf.cc.
Referenced by parseTimeUnit().
T_YEAR_STR
const char* const T_YEAR_STR = "year" static
Definition at line 153 of file cache_cf.cc.
Referenced by parseTimeUnit().