Squid Web Cache: mem_node Class Reference
mem_node Class Reference
#include <mem_node.h>
Public Member Functions
mem_node (int64_t)
~mem_node ()
size_t space () const
int64_t start () const
int64_t end () const
Range< int64_t > dataRange () const
bool contains (int64_t const &location) const
bool canAccept (int64_t const &location) const
bool operator< (mem_node const &rhs) const
Static Public Member Functions
static size_t InUseCount ()
static size_t StoreMemSize ()
Public Attributes
StoreIOBuffer nodeBuffer
char data [SM_PAGE_SIZE]
bool write_pending
Private Member Functions
MEMPROXY_CLASS (mem_node)
Detailed Description
Definition at line 17 of file mem_node.h.
Constructor & Destructor Documentation
mem_node()
mem_node::mem_node (int64_t offset)
Definition at line 47 of file mem_node.cc.
References data.
~mem_node()
mem_node::~mem_node ()
Definition at line 54 of file mem_node.cc.
Member Function Documentation
canAccept()
bool mem_node::canAccept (int64_t const & location) const
Definition at line 105 of file mem_node.cc.
References end(), and space().
Referenced by main(), mem_hdr::nodeToRecieve(), and mem_hdr::writeAvailable().
contains()
bool mem_node::contains (int64_t const & location) const
Definition at line 95 of file mem_node.cc.
References end(), and start().
Referenced by main().
dataRange()
Range< int64_t > mem_node::dataRange () const
Definition at line 83 of file mem_node.cc.
References end(), and start().
Referenced by main().
end()
int64_t mem_node::end () const
Definition at line 77 of file mem_node.cc.
References StoreIOBuffer::length, nodeBuffer, and StoreIOBuffer::offset.
Referenced by canAccept(), contains(), mem_hdr::copyAvailable(), dataRange(), and main().
InUseCount()
size_t mem_node::InUseCount () static
Definition at line 58 of file mem_node.cc.
Referenced by main(), Store::Controller::memoryCacheHasSpaceFor(), and StoreMemSize().
MEMPROXY_CLASS()
mem_node::MEMPROXY_CLASS (mem_node) private
operator<()
bool mem_node::operator< (mem_node const & rhs) const
Definition at line 113 of file mem_node.cc.
References start().
space()
size_t mem_node::space () const
Definition at line 89 of file mem_node.cc.
References StoreIOBuffer::length, nodeBuffer, and SM_PAGE_SIZE.
Referenced by canAccept(), and mem_hdr::writeAvailable().
start()
int64_t mem_node::start () const
Definition at line 70 of file mem_node.cc.
References assert, nodeBuffer, and StoreIOBuffer::offset.
Referenced by contains(), dataRange(), doPages(), main(), and operator<().
StoreMemSize()
size_t mem_node::StoreMemSize () static
Definition at line 64 of file mem_node.cc.
References InUseCount(), and SM_PAGE_SIZE.
Referenced by Store::Controller::getStats(), and snmp_sysFn().
Member Data Documentation
data
char mem_node::data[SM_PAGE_SIZE]
Definition at line 37 of file mem_node.h.
Referenced by mem_node(), and mem_hdr::NodeGet().
nodeBuffer
StoreIOBuffer mem_node::nodeBuffer
Definition at line 35 of file mem_node.h.
Referenced by mem_hdr::copyAvailable(), doPages(), end(), mem_hdr::getBlockContainingLocation(), main(), mem_hdr::nodeToRecieve(), operator<<(), space(), start(), testSplayOfNodes(), mem_hdr::unionNotEmpty(), and mem_hdr::writeAvailable().
write_pending
bool mem_node::write_pending
Definition at line 38 of file mem_node.h.
Referenced by memNodeWriteComplete(), mem_hdr::NodeGet(), and mem_hdr::unlink().
The documentation for this class was generated from the following files:
squid/src/mem_node.h
squid/src/mem_node.cc