Squid Web Cache: MemPoolMalloc Class Reference
MemPoolMalloc Class Reference
Squid Components » Memory Management (Memory Pool Allocator)
#include <PoolMalloc.h>
Public Member Functions
MemPoolMalloc (char const *label, size_t aSize)
~MemPoolMalloc () override
size_t getStats (Mem::PoolStats &) override
bool idleTrigger (int) const override
void clean (time_t) override
void relabel (const char *const aLabel)
void * alloc ()
provide (and reserve) memory suitable for storing one object
void freeOne (void *obj)
return memory reserved by alloc()
int getInUseCount () const
the difference between the number of alloc() and freeOne() calls
void zeroBlocks (const bool doIt)
virtual void setChunkSize (size_t)
XXX: Misplaced – not all allocators have a notion of a "chunk". See MemPoolChunked.
void flushCounters ()
Static Public Member Functions
static size_t RoundedSize (const size_t minSize)
Public Attributes
size_t countAlloc = 0
the number of calls to Mem::Allocator::alloc() since last flush
size_t countSavedAllocs = 0
the number of malloc()/calloc() calls avoided since last flush
size_t countFreeOne = 0
the number of calls to Mem::Allocator::freeOne() since last flush
const char * label
brief description of objects returned by alloc()
const size_t objectSize
the size (in bytes) of objects managed by this allocator
PoolMeter meter
statistics tracked for this allocator
Static Public Attributes
static const size_t FlushLimit = 1000
Flush counters to 'meter' after flush limit allocations.
Protected Member Functions
void * allocate () override
*alloc()
void deallocate (void *) override
freeOne(void *)
Protected Attributes
bool doZero = true
Private Attributes
std::stack< void * > freelist
Detailed Description
Definition at line 36 of file PoolMalloc.h.
Constructor & Destructor Documentation
MemPoolMalloc()
MemPoolMalloc::MemPoolMalloc (char const * label, size_t aSize)
Definition at line 84 of file PoolMalloc.cc.
~MemPoolMalloc()
MemPoolMalloc::~MemPoolMalloc () override
Definition at line 89 of file PoolMalloc.cc.
References assert, clean(), and Mem::Allocator::getInUseCount().
Member Function Documentation
alloc()
void * Mem::Allocator::alloc () inline inherited
Definition at line 44 of file Allocator.h.
References Mem::Allocator::allocate(), Mem::Allocator::countAlloc, Mem::Allocator::flushCounters(), and Mem::Allocator::FlushLimit.
Referenced by Mem::AllocatorProxy::alloc(), authenticateDigestNonceNew(), cbdataInternalAlloc(), memAllocate(), squidaio_close(), squidaio_init(), squidaio_open(), squidaio_read(), squidaio_stat(), squidaio_unlink(), squidaio_write(), and squidaio_xmalloc().
allocate()
void * MemPoolMalloc::allocate () override protected virtual
*alloc()
Implements Mem::Allocator.
Definition at line 24 of file PoolMalloc.cc.
References Mem::PoolMeter::alloc, Mem::Allocator::countSavedAllocs, Mem::Allocator::doZero, freelist, Mem::PoolMeter::idle, Mem::PoolMeter::inuse, Mem::Allocator::meter, Mem::Allocator::objectSize, VALGRIND_MAKE_MEM_DEFINED, VALGRIND_MAKE_MEM_UNDEFINED, xcalloc(), and xmalloc.
clean()
void MemPoolMalloc::clean (time_t) override virtual
Implements Mem::Allocator.
Definition at line 102 of file PoolMalloc.cc.
References Mem::PoolMeter::alloc, freelist, Mem::PoolMeter::idle, Mem::Allocator::meter, and xfree.
Referenced by ~MemPoolMalloc().
deallocate()
void MemPoolMalloc::deallocate (void *) override protected virtual
freeOne(void *)
Implements Mem::Allocator.
Definition at line 50 of file PoolMalloc.cc.
References Mem::PoolMeter::alloc, Mem::Allocator::doZero, freelist, MemPools::GetInstance(), Mem::PoolMeter::idle, Mem::PoolMeter::inuse, Mem::Allocator::meter, Mem::Allocator::objectSize, VALGRIND_MAKE_MEM_NOACCESS, and xfree.
flushCounters()
void Mem::Allocator::flushCounters () inline inherited
Flush temporary counter values into the statistics held in 'meter'.
Definition at line 74 of file Allocator.h.
References Mem::Allocator::countAlloc, Mem::Allocator::countFreeOne, Mem::Allocator::countSavedAllocs, Mem::PoolMeter::gb_allocated, Mem::PoolMeter::gb_freed, Mem::PoolMeter::gb_saved, Mem::Allocator::meter, Mem::Allocator::objectSize, and Mem::PoolMeter::mgb_t::update().
Referenced by MemPoolChunked::~MemPoolChunked(), Mem::Allocator::alloc(), and MemPoolChunked::clean().
freeOne()
void Mem::Allocator::freeOne (void * obj) inline inherited
Definition at line 51 of file Allocator.h.
References assert, Mem::Allocator::countFreeOne, Mem::Allocator::deallocate(), Mem::Allocator::objectSize, and VALGRIND_CHECK_MEM_IS_ADDRESSABLE.
Referenced by cbdata::~cbdata(), authenticateDigestNonceDelete(), memFree(), squidaio_cleanup_request(), and squidaio_cleanup_request().
getInUseCount()
int Mem::Allocator::getInUseCount () const inline inherited
Definition at line 59 of file Allocator.h.
References Mem::Meter::currentLevel(), Mem::PoolMeter::inuse, and Mem::Allocator::meter.
Referenced by MemPoolChunked::~MemPoolChunked(), ~MemPoolMalloc(), MemPoolChunked::getStats(), getStats(), StoreEntry::inUseCount(), and memInUse().
getStats()
size_t MemPoolMalloc::getStats (Mem::PoolStats &) override virtual
fill the given object with statistical data about pool
Returns
Number of objects in use, ie. allocated.
Implements Mem::Allocator.
Definition at line 67 of file PoolMalloc.cc.
References Mem::PoolMeter::alloc, Mem::PoolStats::chunk_capacity, Mem::Meter::currentLevel(), Mem::Allocator::getInUseCount(), Mem::PoolMeter::idle, Mem::PoolMeter::inuse, Mem::PoolStats::items_alloc, Mem::PoolStats::items_idle, Mem::PoolStats::items_inuse, Mem::Allocator::label, Mem::PoolStats::label, Mem::Allocator::meter, Mem::PoolStats::meter, Mem::PoolStats::obj_size, Mem::Allocator::objectSize, Mem::PoolStats::overhead, and Mem::PoolStats::pool.
idleTrigger()
bool MemPoolMalloc::idleTrigger (int shift) const override virtual
Implements Mem::Allocator.
Definition at line 96 of file PoolMalloc.cc.
References freelist.
relabel()
void Mem::Allocator::relabel (const char *const aLabel) inline inherited
change the allocator description if we were only able to provide an approximate description at object construction time
Definition at line 34 of file Allocator.h.
References Mem::Allocator::label.
RoundedSize()
static size_t Mem::Allocator::RoundedSize (const size_t minSize) inline static inherited
Parameters
minSize Minimum size needed to be allocated.
Return values
n Smallest size divisible by sizeof(void*)
Definition at line 93 of file Allocator.h.
setChunkSize()
virtual void Mem::Allocator::setChunkSize (size_t) inline virtual inherited
Reimplemented in MemPoolChunked.
Definition at line 65 of file Allocator.h.
Referenced by Mem::Init().
zeroBlocks()
void Mem::Allocator::zeroBlocks (const bool doIt) inline inherited
See also
doZero
Definition at line 62 of file Allocator.h.
References Mem::Allocator::doZero.
Referenced by Mem::AllocatorProxy::getAllocator(), and memDataInit().
Member Data Documentation
countAlloc
size_t Mem::Allocator::countAlloc = 0 inherited
Definition at line 98 of file Allocator.h.
Referenced by Mem::Allocator::alloc(), and Mem::Allocator::flushCounters().
countFreeOne
size_t Mem::Allocator::countFreeOne = 0 inherited
Definition at line 104 of file Allocator.h.
Referenced by Mem::Allocator::flushCounters(), and Mem::Allocator::freeOne().
countSavedAllocs
size_t Mem::Allocator::countSavedAllocs = 0 inherited
Definition at line 101 of file Allocator.h.
Referenced by allocate(), Mem::Allocator::flushCounters(), and MemPoolChunked::get().
doZero
bool Mem::Allocator::doZero = true protected inherited
Whether to zero memory on initial allocation and on return to the pool.
We do this on some pools because many object constructors are/were incomplete and we are afraid some code may use the object after free. When possible, set this to false to avoid zeroing overheads.
Definition at line 130 of file Allocator.h.
Referenced by MemChunk::MemChunk(), allocate(), deallocate(), MemPoolChunked::push(), and Mem::Allocator::zeroBlocks().
FlushLimit
const size_t Mem::Allocator::FlushLimit = 1000 static inherited
Definition at line 25 of file Allocator.h.
Referenced by Mem::Allocator::alloc().
freelist
std::stack<void *> MemPoolMalloc::freelist private
Definition at line 53 of file PoolMalloc.h.
Referenced by allocate(), clean(), deallocate(), and idleTrigger().
label
const char* Mem::Allocator::label inherited
Definition at line 109 of file Allocator.h.
Referenced by MemPoolChunked::getStats(), getStats(), and Mem::Allocator::relabel().
meter
PoolMeter Mem::Allocator::meter inherited
Definition at line 115 of file Allocator.h.
Referenced by MemChunk::MemChunk(), MemChunk::~MemChunk(), MemPoolChunked::allocate(), allocate(), clean(), MemPoolChunked::deallocate(), deallocate(), Mem::Allocator::flushCounters(), Mem::Allocator::getInUseCount(), MemPoolChunked::getStats(), getStats(), MemPoolChunked::idleTrigger(), and Mem::Report().
objectSize
const size_t Mem::Allocator::objectSize inherited
Definition at line 112 of file Allocator.h.
Referenced by MemChunk::MemChunk(), allocate(), deallocate(), Mem::Allocator::flushCounters(), Mem::Allocator::freeOne(), MemPoolChunked::get(), MemPoolChunked::getStats(), getStats(), MemPoolChunked::push(), and MemPoolChunked::setChunkSize().
The documentation for this class was generated from the following files:
squid/src/mem/PoolMalloc.h
squid/src/mem/PoolMalloc.cc