Squid Web Cache: CommIO Class Reference
CommIO Class Reference
#include <CommIO.h>
Static Public Member Functions
static void NotifyIOCompleted ()
static void ResetNotifications ()
static void Initialize ()
static void NotifyIOClose ()
Static Private Member Functions
static void NULLFDHandler (int, void *)
static void FlushPipe ()
Static Private Attributes
static bool Initialized = false
static bool DoneSignalled = false
static int DoneFD = -1
static int DoneReadFD = -1
Detailed Description
Definition at line 16 of file CommIO.h.
Member Function Documentation
FlushPipe()
void CommIO::FlushPipe () static private
Definition at line 57 of file CommIO.cc.
References DoneReadFD, and FD_READ_METHOD().
Referenced by NotifyIOClose(), NULLFDHandler(), and ResetNotifications().
Initialize()
void CommIO::Initialize () static
Definition at line 21 of file CommIO.cc.
References COMM_SELECT_READ, commSetNonBlocking(), DoneFD, DoneReadFD, fd_open(), FD_PIPE, Initialized, NULLFDHandler(), and Comm::SetSelect().
Referenced by squidaio_init().
NotifyIOClose()
void CommIO::NotifyIOClose () static
Definition at line 40 of file CommIO.cc.
References DoneFD, DoneReadFD, fd_close(), FlushPipe(), Initialized, and xclose().
Referenced by squidaio_shutdown().
NotifyIOCompleted()
void CommIO::NotifyIOCompleted () inline static
Definition at line 36 of file CommIO.h.
References DoneFD, DoneSignalled, fatalf(), FD_WRITE_METHOD(), and Initialized.
Referenced by squidaio_thread_loop(), and squidaio_thread_loop().
NULLFDHandler()
void CommIO::NULLFDHandler (int fd, void *) static private
Definition at line 64 of file CommIO.cc.
References COMM_SELECT_READ, FlushPipe(), NULLFDHandler(), and Comm::SetSelect().
Referenced by Initialize(), and NULLFDHandler().
ResetNotifications()
void CommIO::ResetNotifications () static
Definition at line 71 of file CommIO.cc.
References DoneSignalled, and FlushPipe().
Referenced by squidaio_poll_done().
Member Data Documentation
DoneFD
int CommIO::DoneFD = -1 static private
Definition at line 30 of file CommIO.h.
Referenced by Initialize(), NotifyIOClose(), and NotifyIOCompleted().
DoneReadFD
int CommIO::DoneReadFD = -1 static private
Definition at line 31 of file CommIO.h.
Referenced by FlushPipe(), Initialize(), and NotifyIOClose().
DoneSignalled
bool CommIO::DoneSignalled = false static private
Definition at line 29 of file CommIO.h.
Referenced by NotifyIOCompleted(), and ResetNotifications().
Initialized
bool CommIO::Initialized = false static private
Definition at line 28 of file CommIO.h.
Referenced by Initialize(), NotifyIOClose(), and NotifyIOCompleted().
The documentation for this class was generated from the following files:
squid/src/DiskIO/DiskThreads/CommIO.h
squid/src/DiskIO/DiskThreads/CommIO.cc
squid/src/tests/stub_CommIO.cc