Squid Web Cache: squid/src/auth/digest/eDirectory/digest_pw_auth.cc File Reference
digest_pw_auth.cc File Reference
#include "squid.h"
#include "auth/digest/eDirectory/digest_common.h"
#include "auth/digest/eDirectory/ldap_backend.h"
#include "helper/protocol_defines.h"
Macros
#define PROGRAM_NAME "digest_edirectory_auth"
Functions
static void GetHHA1 (RequestData *requestData)
static void ParseBuffer (char *buf, RequestData *requestData)
static void OutputHHA1 (RequestData *requestData)
static void DoOneRequest (char *buf)
static void ProcessArguments (int argc, char **argv)
int main (int argc, char **argv)
Macro Definition Documentation
PROGRAM_NAME
#define PROGRAM_NAME "digest_edirectory_auth"
Definition at line 43 of file digest_pw_auth.cc.
Function Documentation
DoOneRequest()
static void DoOneRequest (char * buf) static
Definition at line 90 of file digest_pw_auth.cc.
References _request_data::channelId, OutputHHA1(), ParseBuffer(), _request_data::parsed, and SEND_BH.
GetHHA1()
static void GetHHA1 (RequestData * requestData) static
Definition at line 46 of file digest_pw_auth.cc.
References LDAPHHA1().
Referenced by OutputHHA1().
main()
int main (int argc, char ** argv)
Definition at line 111 of file digest_pw_auth.cc.
References DoOneRequest(), HELPER_INPUT_BUFFER, and ProcessArguments().
OutputHHA1()
static void OutputHHA1 (RequestData * requestData) static
Definition at line 76 of file digest_pw_auth.cc.
References _request_data::channelId, _request_data::error, GetHHA1(), _request_data::HHA1, and SEND_ERR.
ParseBuffer()
static void ParseBuffer (char * buf, RequestData * requestData) static
Definition at line 52 of file digest_pw_auth.cc.
References _request_data::channelId, _request_data::parsed, _request_data::realm, strtoll(), and _request_data::user.
Referenced by DoOneRequest().
ProcessArguments()
static void ProcessArguments (int argc, char ** argv) static
Definition at line 104 of file digest_pw_auth.cc.
References LDAPArguments().