Squid Web Cache: squid/src/fatal.h File Reference
fatal.h File Reference
Functions
void fatal (const char *message)
void fatalf (const char *fmt,...) PRINTF_FORMAT_ARG1
void fatal_dump (const char *message)
Function Documentation
fatal()
void fatal (const char * message)
Definition at line 28 of file fatal.cc.
References fatal_common(), leave_suid(), releaseServerSockets(), shutting_down, and storeDirWriteCleanLogs().
Referenced by AuthenticateAcl(), Store::Disks::callback(), Log::TcpLogger::canFit(), clientOpenListenSockets(), configDoConfigure(), Auth::UserRequest::connLastHeader(), Rock::SwapDir::createError(), DelayIdComposite::delayRead(), diskHandleWrite(), Comm::TcpAcceptor::doAccept(), CommonPool::Factory(), fatalvf(), MemStoreRr::finalizeConfig(), Downloader::handleReply(), heap_guessType(), htcpIncomingConnectionOpened(), htcpOpenPorts(), icpIncomingConnectionOpened(), icpLogFromICPCode(), icpOpenPorts(), DiskdIOStrategy::init(), Rock::SwapDir::init(), Fs::Ufs::UFSSwapDir::init(), Store::Disks::init(), SharedMemory::init(), Dns::Init(), MimeIcon::load(), logfile_mod_daemon_open(), logfileHandleWrite(), mainHandleCommandLineOption(), mainReconfigureFinish(), Acl::Node::matchForCache(), Fs::Ufs::UFSSwapDir::openLog(), ACLIP::operator delete(), Acl::Node::operator delete(), Auth::UserRequest::operator delete(), Auth::UserRequest::operator new(), ACLIP::operator new(), Acl::Node::operator new(), SplayConstIterator< V >::operator*(), Security::PeerOptions::parse(), Security::PeerOptions::parseFlags(), Rock::SwapDir::parseSize(), Fs::Ufs::UFSSwapDir::parseSizeL1L2(), peerDigestHandleReply(), ConnStateData::postHttpsAccept(), repl_guessType(), Ftp::Server::replyDataWritingCheckpoint(), setEffectiveUser(), EventLoop::setPrimaryEngine(), snmpOpenPorts(), Http::Stream::socketState(), squidaio_init(), squidaio_poll_queues(), squidaio_queue_request(), squidaio_thread_loop(), SquidMain(), unlinkdInit(), Rock::SwapDir::validateOptions(), StoreEntry::vappendf(), wccp2ConnectionOpen(), wccpConnectionOpen(), and Http::Stream::writeComplete().
fatal_dump()
void fatal_dump (const char * message)
Definition at line 78 of file fatal.cc.
References failure_notify, fatal_common(), leave_suid(), opt_catch_signals, Debug::PrepareToDie(), releaseServerSockets(), and storeDirWriteCleanLogs().
Referenced by EventLoop::checkEngine(), CommSelectEngine::checkEvents(), mem_hdr::copy(), debug_trap(), FwdState::dispatch(), htcpBuildClrOpData(), htcpBuildTstOpData(), setSystemLimits(), SquidMain(), and mem_hdr::write().
fatalf()
void fatalf (const char * fmt, ...)
Definition at line 68 of file fatal.cc.
References fatalvf().
Referenced by accessLogLogTo(), Ipc::Mem::Segment::checkSupport(), Fs::Ufs::UFSSwapDir::closeTmpSwapLog(), configDoConfigure(), Debug::ConfigureSyslog(), Ipc::Mem::Segment::create(), Security::PeerOptions::createBlankContext(), Fs::Ufs::UFSSwapDir::createDirectory(), createRemovalPolicy(), Security::ServerOptions::createSigningContexts(), ConfigParser::destruct(), Comm::TcpAcceptor::doAccept(), EvalBoolExpr(), fd_open(), fdAdjustReserved(), Auth::SchemeConfig::GetParsed(), Helper::Client::handleFewerServers(), DiskdIOStrategy::init(), Ssl::InitClientContext(), Ssl::Initialize(), Security::ServerOptions::initServerContexts(), Rock::SwapDir::ioCompletedNotification(), leave_suid(), MimeIcon::load(), logfile_mod_daemon_flush(), logfile_mod_stdio_open(), logfile_mod_stdio_rotate(), logfile_mod_udp_open(), logfileWriteWrapper(), mainHandleCommandLineOption(), mainSetCwd(), CommIO::NotifyIOCompleted(), Ipc::Mem::Segment::open(), Log::TcpLogger::Open(), OpenedHttpSocket(), Fs::Ufs::UFSSwapDir::openTmpSwapLog(), ACLHierCodeData::parse(), Notes::parse(), Security::PeerOptions::parse(), parse_peer(), parse_wccp2_service_flags(), parse_wccp2_service_info(), parse_wccp2_service_ports(), Ssl::ParseErrorString(), Security::PeerOptions::parseFlags(), Notes::parseKvPair(), parseManyConfigFiles(), Acl::Node::ParseNamed(), parseOneConfigFile(), Security::PeerOptions::parseOptions(), parsePortProtocol(), Adaptation::Config::parseService(), Helper::Client::prepSubmit(), requirePathnameExists(), Comm::SelectLoopInit(), snmpPortOpened(), storeCleanup(), Ipc::Strand::timedout(), watch_child(), wccp2AssignBuckets(), wccp2HandleUdp(), wccp2HereIam(), and wccp2Init().