Squid Web Cache: squid/src/auth/digest/LDAP/ldap_backend.h File Reference
ldap_backend.h File Reference
#include "auth/digest/LDAP/digest_common.h"
Functions
int LDAPArguments (int argc, char **argv)
void LDAPHHA1 (RequestData *requestData)
Function Documentation
LDAPArguments()
int LDAPArguments (int argc, char ** argv) extern
Definition at line 427 of file ldap_backend.cc.
References aliasderef, binddn, bindpasswd, connect_timeout, debug_enabled, delimiter, edir_universal_passwd, encrpass, frealm, ldapServer, noreferrals, passattr, persistent, port, PROGRAM_NAME, readSecret(), searchscope, strip_nt_domain, timelimit, use_tls, userbasedn, userdnattr, usersearchfilter, version, xmalloc, and xstrdup.
Referenced by ProcessArguments().
LDAPHHA1()
void LDAPHHA1 (RequestData * requestData) extern
Definition at line 680 of file ldap_backend.cc.
References delimiter, DigestCalcHA1(), encrpass, _request_data::error, frealm, getpassword(), _request_data::HHA1, ldapconnect(), _request_data::realm, _request_data::user, and xstrncpy().
Referenced by GetHHA1().