Squid Web Cache: squid/src/neighbors.h File Reference
neighbors.h File Reference
#include "anyp/forward.h"
#include "enums.h"
#include "ICP.h"
#include "lookup_t.h"
#include "typedefs.h"
Functions
CachePeer * getFirstUpParent (PeerSelector *)
CachePeer * getSingleParent (PeerSelector *)
int neighborsCount (PeerSelector *)
int neighborsUdpPing (HttpRequest *, StoreEntry *, IRCB *callback, PeerSelector *ps, int *exprep, int *timeout)
void neighborAddAcl (const char *, const char *)
void neighborsUdpAck (const cache_key *, icp_common_t *, const Ip::Address &)
void neighborAdd (const char *, const char *, int, int, int, int, int)
void neighbors_init (void)
void neighborsHtcpClear (StoreEntry *, HttpRequest *, const HttpRequestMethod &, htcp_clr_reason)
CachePeer * findCachePeerByName (const char *)
cache_peer with a given name (or nil)
CachePeer * getDefaultParent (PeerSelector *)
CachePeer * getRoundRobinParent (PeerSelector *)
CachePeer * getWeightedRoundRobinParent (PeerSelector *)
void peerClearRRStart (void)
void peerClearRR (void)
void peerAlive (CachePeer *)
lookup_t peerDigestLookup (CachePeer *p, PeerSelector *)
CachePeer * neighborsDigestSelect (PeerSelector *)
void peerNoteDigestLookup (HttpRequest *request, CachePeer *p, lookup_t lookup)
int neighborUp (const CachePeer *e)
const char * neighborTypeStr (const CachePeer *e)
peer_t neighborType (const CachePeer *, const AnyP::Uri &)
void dump_peer_options (StoreEntry *, CachePeer *)
int peerHTTPOkay (const CachePeer *, PeerSelector *)
time_t positiveTimeout (const time_t timeout)
bool peerCanOpenMore (const CachePeer *p)
Whether we can open new connections to the peer (e.g., despite max-conn)
bool peerHasConnAvailable (const CachePeer *p)
Whether the peer has idle or standby connections that can be used now.
void peerConnClosed (CachePeer *p)
Notifies peer of an associated connection closure.
CachePeer * whichPeer (const Ip::Address &from)
Function Documentation
dump_peer_options()
void dump_peer_options (StoreEntry * sentry, CachePeer * p)
Definition at line 1382 of file neighbors.cc.
References CachePeer::allow_miss, CachePeer::background_ping, CachePeer::carp, CachePeer::closest_only, CachePeer::connect_fail_limit, CachePeer::connect_timeout_raw, CachePeer::connection_auth, CachePeer::default_parent, CachePeer::digest_url, CachePeer::domain, Security::PeerOptions::dumpCfg(), CachePeer::htcp, CachePeer::htcp_forward_clr, CachePeer::htcp_no_clr, CachePeer::htcp_no_purge_clr, CachePeer::htcp_oldsquid, CachePeer::htcp_only_clr, CachePeer::limit, CachePeer::login, CachePeer::max_conn, CachePeer::mcast, CachePeer::mcast_responder, CachePeer::mcast_siblings, CachePeer::no_delay, CachePeer::no_digest, CachePeer::no_netdb_exchange, CachePeer::no_query, CachePeer::no_tproxy, CachePeer::options, CachePeer::originserver, PEER_TCP_MAGIC_COUNT, AsList< Container >::prefixedBy(), CachePeer::proxy_only, CachePeer::roundrobin, CachePeer::secure, CachePeer::sourcehash, CachePeer::standby, CachePeer::ttl, CachePeer::userhash, CachePeer::weight, and CachePeer::weighted_roundrobin.
Referenced by dump_peer(), and dump_peers().
findCachePeerByName()
CachePeer * findCachePeerByName (const char * name)
Definition at line 1048 of file neighbors.cc.
References CurrentCachePeers().
Referenced by ConfigParser::cachePeer(), and parse_peer().
getDefaultParent()
CachePeer * getDefaultParent (PeerSelector * ps)
Definition at line 469 of file neighbors.cc.
References assert, CurrentCachePeers(), debugs, neighborType(), PEER_PARENT, peerHTTPOkay(), PeerSelector::request, and HttpRequest::url.
Referenced by PeerSelector::selectAllParents(), and PeerSelector::selectSomeParent().
getFirstUpParent()
CachePeer * getFirstUpParent (PeerSelector * ps)
Definition at line 282 of file neighbors.cc.
References assert, CurrentCachePeers(), debugs, neighborType(), neighborUp(), PEER_PARENT, peerHTTPOkay(), PeerSelector::request, and HttpRequest::url.
Referenced by PeerSelector::selectSomeParent().
getRoundRobinParent()
CachePeer * getRoundRobinParent (PeerSelector * ps)
Definition at line 308 of file neighbors.cc.
References assert, CurrentCachePeers(), debugs, double, neighborType(), PEER_PARENT, peerHTTPOkay(), RawPointer(), PeerSelector::request, CachePeer::rr_count, HttpRequest::url, and CachePeer::weight.
Referenced by PeerSelector::selectSomeParent().
getSingleParent()
CachePeer * getSingleParent (PeerSelector *)
getWeightedRoundRobinParent()
CachePeer * getWeightedRoundRobinParent (PeerSelector * ps)
Definition at line 350 of file neighbors.cc.
References assert, CachePeer::basetime, CurrentCachePeers(), debugs, neighborType(), PEER_PARENT, peerHTTPOkay(), RawPointer(), PeerSelector::request, CachePeer::rr_count, CachePeer::rtt, CachePeer::stats, HttpRequest::url, and CachePeer::weight.
Referenced by PeerSelector::selectSomeParent().
neighborAdd()
void neighborAdd (const char * , const char * , int , int , int , int , int)
neighborAddAcl()
void neighborAddAcl (const char * , const char *)
neighbors_init()
void neighbors_init (void)
Definition at line 505 of file neighbors.cc.
References CurrentCachePeers(), DBG_IMPORTANT, debugs, DeleteConfigured(), echo_port, Debug::Extra(), getMyHostname(), HttpPortList, icpIncomingConn, Comm::IsConnOpen(), neighborsRegisterWithCacheManager(), peerDnsRefreshStart(), and xgetservbyname().
Referenced by mainInitialize(), and mainReconfigureFinish().
neighborsCount()
int neighborsCount (PeerSelector * ps)
Definition at line 268 of file neighbors.cc.
References CurrentCachePeers(), debugs, and peerWouldBePinged().
Referenced by peerSelectIcpPing().
neighborsDigestSelect()
CachePeer * neighborsDigestSelect (PeerSelector * ps)
Definition at line 749 of file neighbors.cc.
References assert, Config, debugs, HttpRequest::flags, HttpRequest::hier, RequestFlags::hierarchical, LOOKUP_HIT, LOOKUP_MISS, LOOKUP_NONE, HierarchyLogEntry::n_choices, HierarchyLogEntry::n_ichoices, netdbHostRtt(), CachePeers::nextPeerToPing(), peerDigestLookup(), peerNoteDigestLookup(), SquidConfig::peers, PeerSelector::request, CachePeers::size(), and storeKeyPublicByRequest().
Referenced by PeerSelector::selectSomeNeighbor().
neighborsHtcpClear()
void neighborsHtcpClear (StoreEntry * e, HttpRequest * req, const HttpRequestMethod & method, htcp_clr_reason reason)
Definition at line 1675 of file neighbors.cc.
References CurrentCachePeers(), debugs, HTCP_CLR_PURGE, and htcpClear().
Referenced by httpMaybeRemovePublic(), purgeEntriesByUrl(), and clientReplyContext::purgeEntry().
neighborsUdpAck()
void neighborsUdpAck (const cache_key * key, icp_common_t * header, const Ip::Address & from)
I should attach these records to the entry. We take the first hit we get our wait until everyone misses. The timeout handler call needs to nip this shopping list or call one of the misses.
If a hit process is already started, then sobeit
Definition at line 927 of file neighbors.cc.
References CachePeer::icp_::counts, DBG_CRITICAL, DBG_IMPORTANT, debug_trap(), debugs, DeleteConfigured(), EBIT_TEST, ENTRY_DISPATCHED, StoreEntry::flags, CachePeer::icp, ICP_DECHO, ICP_DENIED, ICP_END, ICP_HIT, ICP_MISS, ICP_MISS_NOFETCH, icp_opcode_str, ICP_SECHO, ignoreMulticastReply(), MemObject::ircb_data, StoreEntry::locked(), StoreEntry::mem_obj, neighborAlive(), neighborCountIgnored(), neighborIgnoreNonPeer(), neighborType(), neighborUpdateRtt(), icp_common_t::opcode, PEER_NONE, PEER_SIBLING, MemObject::ping_reply_callback, StoreEntry::ping_status, PING_WAITING, CachePeer::pings_acked, AnyP::PROTO_ICP, RawPointer(), MemObject::request, Store::Root(), CachePeer::stats, storeKeyText(), HttpRequest::url, and whichPeer().
Referenced by icp_common_t::handleReply().
neighborsUdpPing()
int neighborsUdpPing (HttpRequest * request, StoreEntry * entry, IRCB * callback, PeerSelector * ps, int * exprep, int * timeout)
Definition at line 544 of file neighbors.cc.
References assert, Config, CodeContext::Current(), current_time, DBG_CRITICAL, DBG_IMPORTANT, debugs, echo_port, Comm::Connection::fd, StoreEntry::getMD5Text(), StoreEntry::hasDisk(), SquidConfig::htcp, htcpQuery(), SquidConfig::icp, ICP_DECHO, ICP_FLAG_SRC_RTT, ICP_QUERY, SquidConfig::icp_query, SquidConfig::icp_query_max, SquidConfig::icp_query_min, ICP_VERSION_2, icpCreateAndSend(), icpOutgoingConn, icpSetCacheKey(), MemObject::ircb_data, Comm::IsConnOpen(), hash_link::key, mcastSetTtl(), StoreEntry::mem_obj, neighborType(), neighborTypeStr(), neighborUp(), CachePeers::nextPeerToPing(), SquidConfig::onoff, PEER_ALIVE, PEER_DEAD, PEER_MULTICAST, PEER_PARENT, SquidConfig::peers, peerWouldBePinged(), MemObject::ping_reply_callback, SquidConfig::Port, SquidConfig::query_icmp, CodeContext::Reset(), CachePeers::size(), squid_curtime, MemObject::start_ping, SquidConfig::Timeout, HttpRequest::url, and StoreEntry::url().
Referenced by PeerSelector::selectSomeNeighbor().
neighborType()
peer_t neighborType (const CachePeer * p, const AnyP::Uri & url)
Definition at line 117 of file neighbors.cc.
References NeighborTypeDomainList::domain, AnyP::Uri::host(), matchDomainName(), CachePeer::mcast_siblings, NeighborTypeDomainList::next, CachePeer::options, PEER_MULTICAST, PEER_NONE, PEER_SIBLING, CachePeer::type, NeighborTypeDomainList::type, and CachePeer::typelist.
Referenced by findUsableParentAtHostname(), getDefaultParent(), getFirstUpParent(), getRoundRobinParent(), getWeightedRoundRobinParent(), neighborsHtcpReply(), neighborsUdpAck(), neighborsUdpPing(), peerAllowedToUse(), PeerSelector::selectAllParents(), PeerSelector::selectSomeNeighbor(), and HttpStateData::sendRequest().
neighborTypeStr()
const char * neighborTypeStr (const CachePeer * e)
Definition at line 84 of file neighbors.cc.
References PEER_MULTICAST, PEER_NONE, PEER_SIBLING, and CachePeer::type.
Referenced by dump_peer(), dump_peers(), neighborsUdpPing(), CachePeer::noteFailure(), peerAlive(), and peerDNSConfigure().
neighborUp()
int neighborUp (const CachePeer * e)
Definition at line 1058 of file neighbors.cc.
References CallService(), Config, SquidConfig::deadPeer, debugs, CachePeer::n_addresses, CachePeer::no_query, CachePeer::options, CachePeer::probe_start, CachePeer::probeCodeContext, squid_curtime, CachePeer::stats, CachePeer::tcp_up, and SquidConfig::Timeout.
Referenced by dump_peers(), getFirstUpParent(), neighborsUdpPing(), PeerPoolMgr::openNewConnection(), peerHTTPOkay(), peerWouldBePinged(), and snmp_meshPtblFn().
peerAlive()
void peerAlive (CachePeer * p)
Updates protocol-agnostic CachePeer state after an indication of a successful contact with the given cache_peer.
Definition at line 450 of file neighbors.cc.
References PeerPoolMgr::Checkpoint(), DBG_IMPORTANT, debugs, CachePeer::host, ipcache_nbgethostbyname(), CachePeer::last_reply, CachePeer::logged_state, CachePeer::mgr, CachePeer::n_addresses, neighborTypeStr(), PEER_ALIVE, PEER_DEAD, peerClearRR(), peerDNSConfigure, CachePeer::probe_start, squid_curtime, CachePeer::standby, CachePeer::stats, CachePeer::tcp_up, and CbcPointer< Cbc >::valid().
Referenced by neighborAlive(), neighborAliveHtcp(), and CachePeer::noteSuccess().
peerCanOpenMore()
bool peerCanOpenMore (const CachePeer * p)
Definition at line 218 of file neighbors.cc.
References CachePeer::conn_open, debugs, CachePeer::max_conn, Squid_MaxFD, and CachePeer::stats.
Referenced by PeerPoolMgr::openNewConnection(), peerConnClosed(), and peerHTTPOkay().
peerClearRR()
void peerClearRR (void)
Called whenever the round-robin counters need to be reset to a sane state. So far those times are:
On startup and reconfigure - to set the counters to sane initial settings.
When a CachePeer has revived from dead, to prevent the revived CachePeer being flooded with requests which it has 'missed' during the down period.
Definition at line 443 of file neighbors.cc.
References CurrentCachePeers().
Referenced by peerAlive(), and peerClearRRLoop().
peerClearRRStart()
void peerClearRRStart (void)
This gets called on startup and restart to kick off the CachePeer round-robin maintenance event. It ensures that no matter how many times its called no more than one event is scheduled.
Definition at line 426 of file neighbors.cc.
References peerClearRRLoop().
Referenced by parse_peer().
peerConnClosed()
void peerConnClosed (CachePeer * p)
Definition at line 242 of file neighbors.cc.
References PeerPoolMgr::Checkpoint(), CachePeer::conn_open, CachePeer::mgr, peerCanOpenMore(), CachePeer::standby, CachePeer::stats, and CachePeer::waitingForClose.
Referenced by Comm::Connection::noteClosure().
peerDigestLookup()
lookup_t peerDigestLookup (CachePeer * p, PeerSelector * ps)
Definition at line 703 of file neighbors.cc.
References assert, PeerDigest::cd, CacheDigest::contains(), debugs, CachePeer::digest, PeerDigest::flags, LOOKUP_HIT, LOOKUP_MISS, LOOKUP_NONE, PeerDigest::needed, peerDigestNeeded(), peerHTTPOkay(), PeerSelector::request, PeerDigest::requested, storeKeyPublicByRequest(), and PeerDigest::usable.
Referenced by PeerSelector::handleIcpReply(), and neighborsDigestSelect().
peerHasConnAvailable()
bool peerHasConnAvailable (const CachePeer * p)
Definition at line 227 of file neighbors.cc.
References PconnPool::count(), debugs, CachePeer::pool, and CachePeer::standby.
Referenced by peerHTTPOkay().
peerHTTPOkay()
int peerHTTPOkay (const CachePeer * p, PeerSelector * ps)
Definition at line 253 of file neighbors.cc.
References neighborUp(), peerAllowedToUse(), peerCanOpenMore(), and peerHasConnAvailable().
Referenced by carpSelectParent(), findUsableParentAtHostname(), getDefaultParent(), getFirstUpParent(), getRoundRobinParent(), getWeightedRoundRobinParent(), ignoreMulticastReply(), peerDigestLookup(), peerSourceHashSelectParent(), peerUserHashSelectParent(), and PeerSelector::selectAllParents().
peerNoteDigestLookup()
void peerNoteDigestLookup (HttpRequest * request, CachePeer * p, lookup_t lookup)
Definition at line 811 of file neighbors.cc.
References HierarchyLogEntry::cd_host, HierarchyLogEntry::cd_lookup, debugs, HttpRequest::hier, CachePeer::host, lookup_t_str, and RawPointer().
Referenced by PeerSelector::handleIcpReply(), and neighborsDigestSelect().
positiveTimeout()
time_t positiveTimeout (const time_t timeout)
Returns
max(1, timeout)
Definition at line 1092 of file neighbors.cc.
References max().
Referenced by FwdState::connectingTimeout(), and PeerPoolMgr::handleOpenedConnection().
whichPeer()
CachePeer * whichPeer (const Ip::Address & from)
Definition at line 99 of file neighbors.cc.
References CurrentCachePeers(), debugs, and Ip::Address::port().
Referenced by PeerSelector::checkNetdbDirect(), neighborsHtcpReply(), neighborsUdpAck(), and PeerSelector::selectSomeNeighborReplies().