Squid Web Cache: squid/src/PeerDigest.h File Reference
PeerDigest.h File Reference
#include "cbdata.h"
#include "StatCounters.h"
Classes
class Version
class StoreDigestCBlock
class DigestFetchState
class PeerDigest
Functions
void peerDigestNeeded (PeerDigest *pd)
void peerDigestNotePeerGone (PeerDigest *pd)
void peerDigestStatsReport (const PeerDigest *pd, StoreEntry *e)
Variables
const Version CacheDigestVer
Function Documentation
peerDigestNeeded()
void peerDigestNeeded (PeerDigest * pd)
Definition at line 130 of file peer_digest.cc.
References assert, PeerDigest::cd, PeerDigest::flags, PeerDigest::needed, peerDigestSetCheck(), squid_curtime, and PeerDigest::times.
Referenced by peerDigestLookup().
peerDigestNotePeerGone()
void peerDigestNotePeerGone (PeerDigest * pd)
peerDigestStatsReport()
void peerDigestStatsReport (const PeerDigest * pd, StoreEntry * e)
Definition at line 842 of file peer_digest.cc.
References appendTime, assert, cacheDigestGuessStatsReport(), cacheDigestReport(), PeerDigest::cd, f2s, PeerDigest::guess, PeerDigest::host, ByteCounter::kb, PeerDigest::kbytes, PeerDigest::msgs, PeerDigest::recv, PeerDigest::req_delay, PeerDigest::req_result, PeerDigest::retry_delay, PeerDigest::sent, SQUIDSBUFPH, SQUIDSBUFPRINT, PeerDigest::stats, storeAppendPrintf(), and PeerDigest::times.
Referenced by statPeerSelect().
Variable Documentation
CacheDigestVer
const Version CacheDigestVer extern
Definition at line 51 of file peer_digest.cc.
Referenced by peerDigestSetCBlock(), and storeDigestCBlockSwapOut().