Squid Web Cache: squid/src/Store.h File Reference
Store.h File Reference
#include "base/DelayedAsyncCalls.h"
#include "base/Packable.h"
#include "base/Range.h"
#include "base/RefCount.h"
#include "comm/forward.h"
#include "hash.h"
#include "http/forward.h"
#include "http/RequestMethod.h"
#include "HttpReply.h"
#include "MemObject.h"
#include "RemovalPolicy.h"
#include "store/Controller.h"
#include "store/forward.h"
#include "store_key_md5.h"
#include "StoreIOBuffer.h"
#include "StoreStats.h"
#include <ostream>
Classes
class StoreEntry
class Store::EntryGuard
Namespaces
namespace Store
Typedefs
typedef void(* STOREGETCLIENT) (StoreEntry *, void *cbdata)
Functions
std::ostream & operator<< (std::ostream &os, const StoreEntry &e)
void Store::Stats (StoreEntry *output)
void Store::Maintain (void *unused)
size_t storeEntryInUse ()
const char * storeEntryFlags (const StoreEntry *)
void storeEntryReplaceObject (StoreEntry *, HttpReply *)
StoreEntry * storeGetPublic (const char *uri, const HttpRequestMethod &method)
StoreEntry * storeGetPublicByRequest (HttpRequest *request, const KeyScope keyScope=ksDefault)
StoreEntry * storeGetPublicByRequestMethod (HttpRequest *request, const HttpRequestMethod &method, const KeyScope keyScope=ksDefault)
StoreEntry * storeCreateEntry (const char *, const char *, const RequestFlags &, const HttpRequestMethod &)
StoreEntry * storeCreatePureEntry (const char *storeId, const char *logUrl, const HttpRequestMethod &)
void storeInit (void)
void storeConfigure (void)
int expiresMoreThan (time_t, time_t)
void storeAppendPrintf (StoreEntry *, const char *,...) PRINTF_FORMAT_ARG2
void storeAppendVPrintf (StoreEntry *, const char *, va_list ap)
int storeTooManyDiskFilesOpen (void)
void storeHeapPositionUpdate (StoreEntry *, SwapDir *)
void storeSwapFileNumberSet (StoreEntry *e, sfileno filn)
void storeFsInit (void)
void storeFsDone (void)
void storeReplAdd (const char *, REMOVALPOLICYCREATE *)
void storeGetMemSpace (int size)
Variables
StoreIoStats store_io_stats
FREE destroyStoreEntry
Typedef Documentation
STOREGETCLIENT
typedef void(* STOREGETCLIENT) (StoreEntry *, void *cbdata)
Definition at line 343 of file Store.h.
Function Documentation
expiresMoreThan()
int expiresMoreThan (time_t expires, time_t when)
Definition at line 1338 of file store.cc.
References squid_curtime.
operator<<()
std::ostream & operator<< (std::ostream & os, const StoreEntry & e)
Definition at line 337 of file store.cc.
storeAppendPrintf()
void storeAppendPrintf (StoreEntry * e, const char * fmt, ...)
Definition at line 855 of file store.cc.
References StoreEntry::vappendf().
Referenced by DiskThreadsIOStrategy::aioStats(), cacheDigestGuessStatsReport(), cacheDigestReport(), carpCachemgr(), clientdbDump(), Mgr::CloseKidSection(), commIncomingStats(), commIncomingStats(), commIncomingStats(), commIncomingStats(), Auth::User::CredentialsCacheStats(), Store::Disks::Dump(), Fs::Ufs::UFSSwapDir::dump(), Ipc::ReadWriteLockStats::dump(), DelaySpec::dump(), Auth::SchemeConfig::dump(), DelayPool::dump(), MessageDelayPool::dump(), DiskdAction::dump(), Mgr::MenuAction::dump(), Mgr::ReconfigureAction::dump(), Mgr::RotateAction::dump(), Mgr::OfflineToggleAction::dump(), Mgr::StoreIoAction::dump(), Format::Format::dump(), ClientDelayPool::dump(), dump_access_log(), dump_acl_address(), dump_acl_b_size_t(), dump_acl_tos(), dump_address(), dump_b_int64_t(), dump_b_size_t(), dump_b_ssize_t(), dump_cachemgrpasswd(), dump_CpuAffinityMap(), dump_denyinfo(), dump_externalAclHelper(), dump_generic_port(), dump_HeaderWithAclList(), dump_icap_service_failure_limit(), dump_int(), dump_int64_t(), dump_IpAddress_list(), dump_kb_int64_t(), dump_memcachemode(), dump_onoff(), dump_peer(), dump_peers(), dump_PortCfg(), dump_refreshpattern(), dump_removalpolicy(), dump_sslproxy_cert_adapt(), dump_sslproxy_cert_sign(), dump_string(), dump_time_nanoseconds(), dump_tristate(), dump_u_short(), dump_uri_whitespace(), dump_UrlHelperTimeout(), dump_wccp2_amethod(), dump_wccp2_method(), dump_wccp2_service(), dump_wccp2_service_info(), dump_wordlist(), DumpAvgStat(), DumpCountersStats(), DumpInfo(), DumpIoStats(), DumpMallocStatistics(), ClientDelayConfig::dumpPoolCount(), DelayConfig::dumpPoolCount(), Rock::SwapDir::dumpRateOption(), Adaptation::Config::dumpService(), Adaptation::Config::DumpServiceGroups(), DumpServiceTimesStats(), Rock::SwapDir::dumpSizeOption(), fde::dumpStats(), fde::DumpStats(), Rock::SwapDir::dumpTimeOption(), externalAclStats(), fqdnStats(), fwdStats(), header_mangler_dump_access(), header_mangler_dump_replacement(), httpHdrCcStatDumper(), httpHdrScStatDumper(), httpHdrScTargetStatDumper(), httpHeaderFieldStatDumper(), httpHeaderFldsPerHdrDumper(), httpHeaderStatDump(), httpHeaderStoreReport(), idnsStats(), ipcacheStatPrint(), lru_stats(), netdbBinaryExchange(), netdbDump(), Mgr::OpenKidSection(), Fs::Ufs::UFSSwapDir::optionIODump(), Store::Disk::optionObjectSizeDump(), DiskdIOStrategy::optionQ1Dump(), DiskdIOStrategy::optionQ2Dump(), Store::Disk::optionReadOnlyDump(), peerDigestStatsReport(), peerSourceHashCachemgr(), peerUserHashCachemgr(), redirectStats(), refreshCountsStats(), refreshCountsStatsEntry(), refreshStats(), squidaio_stats(), Store::Controller::stat(), Store::Disk::stat(), Store::Disks::stat(), MemStore::stat(), Transients::stat(), stat_ipcache_get(), statClientRequests(), statCountersHistograms(), statDigestBlob(), Fs::Ufs::UFSSwapDir::statfs(), Rock::SwapDir::statfs(), DiskdIOStrategy::statfs(), statHistBinDumper(), statHistEnumDumper(), statHistIntDumper(), statHistSBufDumper(), statPeerSelect(), DelayPools::Stats(), ClassCBucket::stats(), DelayBucket::stats(), DelayTaggedBucket::stats(), DelayUserBucket::stats(), Aggregate::stats(), VectorPool::stats(), ClassCHostPool::stats(), DelayTagged::stats(), DelayUser::stats(), DelaySpec::stats(), statUtilization(), storeCheckCachableStats(), storeDigestReport(), storeIdStats(), and storeLogTagsHist().
storeAppendVPrintf()
void storeAppendVPrintf (StoreEntry * e, const char * fmt, va_list ap)
Definition at line 865 of file store.cc.
References StoreEntry::vappendf().
storeConfigure()
void storeConfigure (void)
Definition at line 1270 of file store.cc.
References Store::Controller::configure(), and Store::Root().
Referenced by configDoConfigure(), and storeSwapOutFileClosed().
storeCreateEntry()
StoreEntry * storeCreateEntry (const char * url, const char * logUrl, const RequestFlags & flags, const HttpRequestMethod & method)
Like storeCreatePureEntry(), but also locks the entry and sets entry key.
Definition at line 759 of file store.cc.
References RequestFlags::cachable, RequestFlags::hierarchical, StoreEntry::lock(), neighbors_do_private_keys, StoreEntry::setPrivateKey(), StoreEntry::setPublicKey(), and storeCreatePureEntry().
Referenced by Ssl::ServerBump::ServerBump(), StoreEntry::adjustVary(), TestRock::createEntry(), Mgr::Action::createStoreEntry(), clientReplyContext::createStoreEntry(), ClientHttpRequest::doCallouts(), netdbExchangeStart(), peerCountMcastPeersCreateAndSend(), peerDigestRequest(), clientReplyContext::processExpired(), UrnState::start(), storeDigestRewriteStart(), and TestUfs::testUfsSearch().
storeCreatePureEntry()
StoreEntry * storeCreatePureEntry (const char * storeId, const char * logUrl, const HttpRequestMethod & method)
Creates a new StoreEntry with mem_obj and sets initial flags/states.
Definition at line 741 of file store.cc.
References StoreEntry::createMemObject(), debugs, EBIT_SET, ENTRY_VALIDATED, StoreEntry::flags, StoreEntry::lastref, PING_NONE, StoreEntry::ping_status, StoreEntry::refcount, squid_curtime, STORE_PENDING, StoreEntry::store_status, and StoreEntry::timestamp.
Referenced by MimeIcon::load(), and storeCreateEntry().
storeEntryFlags()
const char * storeEntryFlags (const StoreEntry * entry)
Definition at line 253 of file stat.cc.
References DELAY_SENDING, EBIT_TEST, ENTRY_ABORTED, ENTRY_BAD_LENGTH, ENTRY_DISPATCHED, ENTRY_FWD_HDR_WAIT, ENTRY_NEGCACHED, ENTRY_REVALIDATE_ALWAYS, ENTRY_REVALIDATE_STALE, ENTRY_SPECIAL, ENTRY_VALIDATED, StoreEntry::flags, int, KEY_PRIVATE, LOCAL_ARRAY, REFRESH_REQUEST, and RELEASE_REQUEST.
Referenced by StoreEntry::dump(), and statStoreEntry().
storeEntryInUse()
size_t storeEntryInUse ()
storeEntryReplaceObject()
void storeEntryReplaceObject (StoreEntry * , HttpReply *)
storeFsDone()
void storeFsDone (void)
storeFsInit()
void storeFsInit (void)
Definition at line 1636 of file store.cc.
References storeReplSetup().
Referenced by SquidMain().
storeGetMemSpace()
void storeGetMemSpace (int size)
Clear Memory storage to accommodate the given object len
Definition at line 1121 of file store.cc.
References Store::Controller::freeMemorySpace(), Store::Root(), and size.
Referenced by store_client::maybeWriteFromDiskToMemory(), and StoreEntry::write().
storeGetPublic()
StoreEntry * storeGetPublic (const char * uri, const HttpRequestMethod & method)
Definition at line 504 of file store.cc.
References assert, debugs, StoreEntry::destroyMemObject(), Store::Disk::disconnect(), StoreEntry::disk(), Store::Controller::find(), StoreEntry::hasDisk(), StoreEntry::hashDelete(), hash_link::key, Store::Root(), and storeKeyPublic().
Referenced by StoreEntry::adjustVary(), findPreviouslyCachedEntry(), TestRock::getEntry(), httpMaybeRemovePublic(), ICPState::isHit(), MimeIcon::load(), clientReplyContext::purgeDoPurge(), UrnState::start(), and urnParseReply().
storeGetPublicByRequest()
StoreEntry * storeGetPublicByRequest (HttpRequest * request, const KeyScope keyScope = ksDefault)
Definition at line 516 of file store.cc.
References HttpRequest::method, Http::METHOD_GET, Http::METHOD_HEAD, and storeGetPublicByRequestMethod().
Referenced by htcpSpecifier::checkHit(), findPreviouslyCachedEntry(), htcpClrStore(), clientReplyContext::identifyStoreObject(), peerDigestRequest(), and clientReplyContext::processExpired().
storeGetPublicByRequestMethod()
StoreEntry * storeGetPublicByRequestMethod (HttpRequest * request, const HttpRequestMethod & method, const KeyScope keyScope = ksDefault)
Definition at line 510 of file store.cc.
References Store::Controller::find(), Store::Root(), and storeKeyPublicByRequestMethod().
Referenced by httpMaybeRemovePublic(), clientReplyContext::purgeDoPurge(), and storeGetPublicByRequest().
storeHeapPositionUpdate()
void storeHeapPositionUpdate (StoreEntry * , SwapDir *)
storeInit()
void storeInit (void)
Definition at line 1257 of file store.cc.
References Config, createRemovalPolicy(), eventAdd(), Store::Controller::init(), mem_policy, SquidConfig::memPolicy, Store::Root(), storeDigestInit(), storeLateRelease, storeLogOpen(), storeRebuildStart(), and storeRegisterWithCacheManager().
Referenced by mainInitialize().
storeReplAdd()
void storeReplAdd (const char * type, REMOVALPOLICYCREATE * create)
Definition at line 1645 of file store.cc.
References _storerepl_entry::create, DBG_IMPORTANT, debugs, storerepl_list, _storerepl_entry::typestr, and xrealloc().
Referenced by TestUfs::commonInit().
storeSwapFileNumberSet()
void storeSwapFileNumberSet (StoreEntry * e, sfileno filn)
storeTooManyDiskFilesOpen()
int storeTooManyDiskFilesOpen (void)
Definition at line 889 of file store.cc.
References Config, SquidConfig::max_open_disk_fds, and store_open_disk_fd.
Referenced by StoreEntry::checkCachable(), store_client::startSwapin(), and StoreEntry::swapOut().
Variable Documentation
destroyStoreEntry
FREE destroyStoreEntry extern
One of the three methods to get rid of an unlocked StoreEntry object. This low-level method ignores lock()ing and release() promises. It never leaves the entry in the local store_table. TODO: Hide by moving its functionality into the StoreEntry destructor.
Referenced by MemStore::get(), Store::Controller::handleIdleEntry(), and StoreEntry::release().
store_io_stats
StoreIoStats store_io_stats extern
Definition at line 16 of file store_io.cc.
Referenced by Mgr::StoreIoAction::collect(), and storeCreate().